packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  core-js: set this to true or false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
