ALTER TABLE "QuotationLineItem" ADD COLUMN "taxAmount" DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE "QuotationLineItem" ADD COLUMN "discountAmount" DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE "QuotationLineItem" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
