import { WorkflowTemplateDefinition } from './system-templates';

/**
 * Dedicated system workflows for the remaining eight services (Phase 5).
 * Version 4 so they outrank the version-3 generic fallback templates that
 * may already exist for these service types; running instances remain
 * pinned to the version they started with.
 */
const V = 4;

export const INSURANCE_TEMPLATE: WorkflowTemplateDefinition = {
  serviceTypeCode: 'INSURANCE',
  code: 'INSURANCE_STANDARD',
  name: 'Travel Insurance — Standard',
  description: 'Enquiry to policy delivery, amendments and insurer reconciliation',
  version: V,
  stages: [
    { code: 'ENQUIRY_RECEIVED', name: 'Insurance Enquiry Received', group: 'INTAKE', slaHours: 2, isInitial: true },
    { code: 'TRIP_DETAILS_COLLECTED', name: 'Traveller and Trip Details Collected', group: 'INTAKE' },
    { code: 'POLICIES_COMPARED', name: 'Available Policies Compared', group: 'QUOTATION', slaHours: 8 },
    { code: 'COVERAGE_EXPLAINED', name: 'Coverage and Exclusions Explained', group: 'QUOTATION', requiredChecklist: [{ code: 'EXCLUSIONS_EXPLAINED', title: 'Coverage limits and exclusions explained to the customer' }] },
    { code: 'QUOTATION_SENT', name: 'Quotation Sent', group: 'QUOTATION', slaHours: 24 },
    { code: 'POLICY_SELECTED', name: 'Policy Selected', group: 'QUOTATION' },
    { code: 'DECLARATIONS_CONFIRMED', name: 'Customer Declarations Confirmed', group: 'DOCUMENTATION', requiredChecklist: [{ code: 'DECLARATIONS', title: 'Health and travel declarations confirmed by the customer' }] },
    { code: 'TRAVELLER_INFO_VERIFIED', name: 'Traveller Information Verified', group: 'DOCUMENTATION', requiredChecklist: [{ code: 'NAME_VERIFICATION', title: 'Traveller names verified against passports' }] },
    { code: 'PAYMENT_RECEIVED', name: 'Payment Received', group: 'PAYMENT', requiresPayment: true },
    { code: 'POLICY_REQUESTED', name: 'Policy Requested', group: 'BOOKING', slaHours: 12 },
    { code: 'POLICY_ISSUED', name: 'Policy Issued', group: 'DELIVERY' },
    { code: 'POLICY_DELIVERED', name: 'Policy Delivered', group: 'DELIVERY', extraNextStageCodes: ['AMENDMENT_OR_EXTENSION', 'CLAIM_ASSISTANCE'] },
    { code: 'AMENDMENT_OR_EXTENSION', name: 'Amendment or Extension', group: 'AFTER_SALES', isSideStage: true, extraNextStageCodes: ['POLICY_DELIVERED'] },
    { code: 'CLAIM_ASSISTANCE', name: 'Claim Assistance', group: 'AFTER_SALES', isSideStage: true, extraNextStageCodes: ['POLICY_DELIVERED'] },
    { code: 'INSURER_RECONCILIATION', name: 'Insurer Reconciliation', group: 'AFTER_SALES' },
    { code: 'CASE_CLOSED', name: 'Case Closed', group: 'CLOSURE', isTerminal: true },
  ],
};

export const TRANSFER_TEMPLATE: WorkflowTemplateDefinition = {
  serviceTypeCode: 'TRANSFER',
  code: 'TRANSFER_STANDARD',
  name: 'Airport Transfer — Standard',
  description: 'Request to trip completion, extra charges and supplier reconciliation',
  version: V,
  stages: [
    { code: 'REQUEST_RECEIVED', name: 'Transfer Request Received', group: 'INTAKE', slaHours: 1, isInitial: true },
    { code: 'PICKUP_DROPOFF_COLLECTED', name: 'Pickup and Drop-Off Collected', group: 'INTAKE' },
    { code: 'ROUTE_ASSESSED', name: 'Route Assessed', group: 'PROCESSING' },
    { code: 'VEHICLE_SELECTED', name: 'Vehicle Requirement Selected', group: 'PROCESSING' },
    { code: 'SUPPLIER_AVAILABILITY', name: 'Supplier Availability Checked', group: 'BOOKING', slaHours: 4 },
    { code: 'QUOTATION_SENT', name: 'Quotation Sent', group: 'QUOTATION', slaHours: 12 },
    { code: 'CUSTOMER_CONFIRMED', name: 'Customer Confirmation', group: 'QUOTATION' },
    { code: 'PAYMENT_APPROVED', name: 'Payment or Credit Approved', group: 'PAYMENT', requiresPayment: true },
    { code: 'SUPPLIER_ASSIGNED', name: 'Supplier Assigned', group: 'BOOKING' },
    { code: 'VEHICLE_ASSIGNED', name: 'Vehicle Assigned', group: 'BOOKING' },
    { code: 'DRIVER_ASSIGNED', name: 'Driver Assigned', group: 'BOOKING', requiredChecklist: [{ code: 'DRIVER_DETAILS', title: 'Driver name, phone and vehicle registration recorded' }] },
    { code: 'PASSENGER_NOTIFIED', name: 'Passenger Notified', group: 'DELIVERY' },
    { code: 'DRIVER_DISPATCHED', name: 'Driver Dispatched', group: 'DELIVERY' },
    { code: 'DRIVER_ARRIVED', name: 'Driver Arrived', group: 'DELIVERY' },
    { code: 'PASSENGER_PICKED_UP', name: 'Passenger Picked Up', group: 'DELIVERY' },
    { code: 'TRIP_IN_PROGRESS', name: 'Trip In Progress', group: 'DELIVERY' },
    { code: 'TRANSFER_COMPLETED', name: 'Transfer Completed', group: 'DELIVERY' },
    { code: 'EXTRA_CHARGES_REVIEWED', name: 'Extra Charges Reviewed', group: 'AFTER_SALES' },
    { code: 'SUPPLIER_RECONCILIATION', name: 'Supplier Reconciliation', group: 'AFTER_SALES' },
    { code: 'CASE_CLOSED', name: 'Case Closed', group: 'CLOSURE', isTerminal: true },
  ],
};

export const UMRAH_TEMPLATE: WorkflowTemplateDefinition = {
  serviceTypeCode: 'UMRAH',
  code: 'UMRAH_STANDARD',
  name: 'Umrah Package — Standard',
  description: 'Enquiry to pilgrim return and supplier reconciliation',
  version: V,
  stages: [
    { code: 'ENQUIRY_RECEIVED', name: 'Umrah Enquiry Received', group: 'INTAKE', slaHours: 4, isInitial: true },
    { code: 'PACKAGE_REQUIREMENTS', name: 'Package Requirement Collected', group: 'INTAKE' },
    { code: 'PACKAGE_SELECTED', name: 'Package Selected', group: 'QUOTATION' },
    { code: 'GROUP_BOOKING_CREATED', name: 'Family or Group Booking Created', group: 'BOOKING' },
    { code: 'PILGRIM_PROFILES', name: 'Pilgrim Profiles Created', group: 'DOCUMENTATION', requiredChecklist: [{ code: 'PILGRIM_PROFILES', title: 'All pilgrim profiles created with passport names' }] },
    { code: 'DOCUMENTS_REQUESTED', name: 'Documents Requested', group: 'DOCUMENTATION', slaHours: 72 },
    { code: 'DOCUMENTS_VERIFIED', name: 'Documents Verified', group: 'DOCUMENTATION', requiredDocumentTypes: ['PASSPORT', 'PHOTO'] },
    { code: 'DEPOSIT_RECEIVED', name: 'Deposit Received', group: 'PAYMENT', requiresPayment: true },
    { code: 'VISA_PROCESSING', name: 'Visa Processing Started', group: 'PROCESSING', slaHours: 168 },
    { code: 'VISA_APPROVED', name: 'Visa Approved', group: 'PROCESSING' },
    { code: 'FLIGHT_RESERVED', name: 'Flight Reserved', group: 'BOOKING' },
    { code: 'FLIGHT_ISSUED', name: 'Flight Issued', group: 'BOOKING' },
    { code: 'MAKKAH_HOTEL_CONFIRMED', name: 'Makkah Hotel Confirmed', group: 'BOOKING' },
    { code: 'MADINAH_HOTEL_CONFIRMED', name: 'Madinah Hotel Confirmed', group: 'BOOKING' },
    { code: 'GROUND_TRANSPORT_CONFIRMED', name: 'Ground Transport Confirmed', group: 'BOOKING' },
    { code: 'ROOM_ALLOCATION', name: 'Room Allocation', group: 'PROCESSING', requiredChecklist: [{ code: 'ROOMS_ALLOCATED', title: 'Rooms and sharing arrangements allocated for all pilgrims' }] },
    { code: 'GROUP_BUS_ASSIGNMENT', name: 'Group and Bus Assignment', group: 'PROCESSING' },
    { code: 'FINAL_PAYMENT_RECEIVED', name: 'Final Payment Received', group: 'PAYMENT', requiresPayment: true },
    { code: 'PRE_DEPARTURE_ORIENTATION', name: 'Pre-Departure Orientation', group: 'DELIVERY' },
    { code: 'TRAVEL_DOCS_DELIVERED', name: 'Travel Documents Delivered', group: 'DELIVERY', requiredChecklist: [{ code: 'DOCS_PACK', title: 'Tickets, vouchers, visa copies and ID cards delivered' }] },
    { code: 'PILGRIMS_DEPARTED', name: 'Pilgrims Departed', group: 'DELIVERY' },
    { code: 'SAUDI_GROUND_OPERATION', name: 'Saudi Ground Operation', group: 'DELIVERY' },
    { code: 'RETURN_FLIGHT_CONFIRMED', name: 'Return Flight Confirmed', group: 'DELIVERY' },
    { code: 'PILGRIMS_RETURNED', name: 'Pilgrims Returned', group: 'AFTER_SALES' },
    { code: 'SUPPLIER_RECONCILIATION', name: 'Supplier Reconciliation', group: 'AFTER_SALES' },
    { code: 'CASE_CLOSED', name: 'Case Closed', group: 'CLOSURE', isTerminal: true },
  ],
};

export const HAJJ_TEMPLATE: WorkflowTemplateDefinition = {
  serviceTypeCode: 'HAJJ',
  code: 'HAJJ_STANDARD',
  name: 'Hajj Package — Standard',
  description: 'Pre-registration to pilgrim return; jurisdiction-specific steps stay configurable per tenant',
  version: V,
  stages: [
    { code: 'ENQUIRY_RECEIVED', name: 'Hajj Enquiry Received', group: 'INTAKE', slaHours: 8, isInitial: true },
    { code: 'PRE_REGISTRATION', name: 'Pre-Registration', group: 'INTAKE' },
    { code: 'ELIGIBILITY_VERIFIED', name: 'Eligibility Verified', group: 'QUALIFICATION', requiredChecklist: [{ code: 'ELIGIBILITY', title: 'Eligibility criteria verified' }] },
    { code: 'PACKAGE_COUNSELLING', name: 'Package Counselling', group: 'QUALIFICATION' },
    { code: 'OFFICIAL_REGISTRATION', name: 'Official Registration', group: 'PROCESSING' },
    { code: 'QUOTA_VERIFIED', name: 'Quota Allocation Verified', group: 'APPROVAL', requiresApproval: true },
    { code: 'AGREEMENT_SIGNED', name: 'Agreement Signed', group: 'DOCUMENTATION', requiredChecklist: [{ code: 'AGREEMENT', title: 'Package agreement signed and archived' }] },
    { code: 'DEPOSIT_RECEIVED', name: 'Deposit Received', group: 'PAYMENT', requiresPayment: true },
    { code: 'DOCUMENTS_VERIFIED', name: 'Documents Verified', group: 'DOCUMENTATION', requiredDocumentTypes: ['PASSPORT', 'PHOTO'] },
    { code: 'GOVERNMENT_PROCESSING', name: 'Government Processing', group: 'PROCESSING' },
    { code: 'GOVERNMENT_PAYMENTS', name: 'Government Payments Completed', group: 'PAYMENT', requiredChecklist: [{ code: 'GOVT_PAYMENTS', title: 'Government fees and payments completed' }] },
    { code: 'VISA_PROCESSING', name: 'Visa Processing', group: 'PROCESSING' },
    { code: 'VISA_ISSUED', name: 'Visa Issued', group: 'PROCESSING' },
    { code: 'FLIGHT_ASSIGNMENT', name: 'Flight Assignment', group: 'BOOKING' },
    { code: 'MAKKAH_ACCOMMODATION', name: 'Makkah Accommodation Assignment', group: 'BOOKING' },
    { code: 'MADINAH_ACCOMMODATION', name: 'Madinah Accommodation Assignment', group: 'BOOKING' },
    { code: 'MASHAIR_ARRANGEMENT', name: 'Mashair Arrangement', group: 'BOOKING' },
    { code: 'ROOM_ASSIGNMENT', name: 'Room Assignment', group: 'PROCESSING' },
    { code: 'GROUP_LEADER_ASSIGNMENT', name: 'Group Leader Assignment', group: 'PROCESSING' },
    { code: 'BUS_ASSIGNMENT', name: 'Bus Assignment', group: 'PROCESSING' },
    { code: 'TRAINING_ORIENTATION', name: 'Training and Orientation', group: 'DELIVERY' },
    { code: 'FINAL_PAYMENT', name: 'Final Payment', group: 'PAYMENT', requiresPayment: true },
    { code: 'FINAL_DOCS_DELIVERED', name: 'Final Documents Delivered', group: 'DELIVERY', requiredChecklist: [{ code: 'DOCS_PACK', title: 'Final travel documents delivered to all pilgrims' }] },
    { code: 'AIRPORT_REPORTING', name: 'Airport Reporting', group: 'DELIVERY' },
    { code: 'DEPARTURE', name: 'Departure', group: 'DELIVERY' },
    { code: 'SAUDI_OPERATION', name: 'Saudi Operation', group: 'DELIVERY' },
    { code: 'MASHAIR_OPERATIONS', name: 'Mina, Arafat and Muzdalifah Operations', group: 'DELIVERY' },
    { code: 'RETURN_FLIGHT', name: 'Return Flight', group: 'DELIVERY' },
    { code: 'PILGRIM_ARRIVAL', name: 'Pilgrim Arrival', group: 'AFTER_SALES' },
    { code: 'RECONCILIATION', name: 'Reconciliation', group: 'AFTER_SALES' },
    { code: 'CASE_CLOSED', name: 'Case Closed', group: 'CLOSURE', isTerminal: true },
  ],
};

export const MEDICAL_TOURISM_TEMPLATE: WorkflowTemplateDefinition = {
  serviceTypeCode: 'MEDICAL_TOURISM',
  code: 'MEDICAL_TOURISM_STANDARD',
  name: 'Medical Tourism — Standard',
  description: 'Consent-first medical coordination; the platform never diagnoses',
  version: V,
  stages: [
    { code: 'ENQUIRY_RECEIVED', name: 'Medical Enquiry Received', group: 'INTAKE', slaHours: 4, isInitial: true },
    { code: 'PATIENT_CONSENT', name: 'Patient Consent Recorded', group: 'DOCUMENTATION', requiredChecklist: [{ code: 'CONSENT_RECORDED', title: 'Explicit consent recorded before sharing any medical data' }] },
    { code: 'MEDICAL_DOCS_REQUESTED', name: 'Medical Documents Requested', group: 'DOCUMENTATION', slaHours: 72 },
    { code: 'MEDICAL_DOCS_RECEIVED', name: 'Medical Documents Received', group: 'DOCUMENTATION' },
    { code: 'COMPLETENESS_REVIEW', name: 'Completeness Review', group: 'DOCUMENTATION', requiredDocumentTypes: ['MEDICAL_REPORT'] },
    { code: 'HOSPITAL_MATCHING', name: 'Hospital or Doctor Matching', group: 'PROCESSING' },
    { code: 'CASE_SHARED_SECURELY', name: 'Case Shared Securely', group: 'PROCESSING', requiredChecklist: [{ code: 'SECURE_SHARE', title: 'Case shared through a secure, access-controlled channel' }] },
    { code: 'PRELIMINARY_OPINION', name: 'Preliminary Medical Opinion Received', group: 'PROCESSING', slaHours: 72 },
    { code: 'TREATMENT_ESTIMATE', name: 'Treatment Estimate Received', group: 'QUOTATION' },
    { code: 'PROPOSAL_PRESENTED', name: 'Proposal Presented', group: 'QUOTATION' },
    { code: 'PATIENT_SELECTION', name: 'Patient Selection', group: 'QUOTATION' },
    { code: 'DEPOSIT_RECEIVED', name: 'Deposit Received', group: 'PAYMENT', requiresPayment: true },
    { code: 'APPOINTMENT_CONFIRMED', name: 'Appointment Confirmed', group: 'BOOKING' },
    { code: 'MEDICAL_VISA_SUPPORT', name: 'Medical Visa Support', group: 'PROCESSING' },
    { code: 'TRAVEL_ARRANGED', name: 'Flight, Hotel and Transfer Arranged', group: 'BOOKING' },
    { code: 'PRE_TRAVEL_COORDINATION', name: 'Pre-Travel Coordination', group: 'DELIVERY' },
    { code: 'PATIENT_ARRIVAL', name: 'Patient Arrival', group: 'DELIVERY' },
    { code: 'ADMISSION_CONSULTATION', name: 'Hospital Admission or Consultation', group: 'DELIVERY' },
    { code: 'TREATMENT_COORDINATION', name: 'Treatment Coordination', group: 'DELIVERY' },
    { code: 'DISCHARGE_COORDINATION', name: 'Discharge Coordination', group: 'DELIVERY' },
    { code: 'FOLLOW_UP_ARRANGED', name: 'Follow-Up Arranged', group: 'AFTER_SALES' },
    { code: 'RETURN_TRAVEL', name: 'Return Travel', group: 'AFTER_SALES' },
    { code: 'FINANCIAL_RECONCILIATION', name: 'Financial Reconciliation', group: 'AFTER_SALES' },
    { code: 'SECURE_CASE_CLOSURE', name: 'Secure Case Closure', group: 'CLOSURE', isTerminal: true },
  ],
};

export const STUDENT_VISA_TEMPLATE: WorkflowTemplateDefinition = {
  serviceTypeCode: 'STUDENT_VISA',
  code: 'STUDENT_VISA_STANDARD',
  name: 'Student Visa — Standard',
  description: 'Counselling to enrolment confirmation and commission tracking',
  version: V,
  stages: [
    { code: 'ENQUIRY_RECEIVED', name: 'Student Enquiry Received', group: 'INTAKE', slaHours: 4, isInitial: true },
    { code: 'ACADEMIC_PROFILE', name: 'Academic Profile Collected', group: 'INTAKE' },
    { code: 'PROFILE_ASSESSMENT', name: 'Profile Assessment', group: 'QUALIFICATION' },
    { code: 'COUNSELLING', name: 'Counselling Completed', group: 'QUALIFICATION' },
    { code: 'PREFERENCES_RECORDED', name: 'Country and Course Preferences Recorded', group: 'QUALIFICATION' },
    { code: 'AGREEMENT_SIGNED', name: 'Student Agreement Signed', group: 'DOCUMENTATION', requiredChecklist: [{ code: 'AGREEMENT', title: 'Service agreement signed by the student' }] },
    { code: 'CHECKLIST_GENERATED', name: 'Document Checklist Generated', group: 'DOCUMENTATION' },
    { code: 'DOCUMENTS_COLLECTED', name: 'Documents Collected', group: 'DOCUMENTATION', requiredDocumentTypes: ['ACADEMIC_TRANSCRIPT', 'PASSPORT'] },
    { code: 'SHORTLIST_CREATED', name: 'Institution Shortlist Created', group: 'PROCESSING' },
    { code: 'SHORTLIST_APPROVED', name: 'Student Approval of Shortlist', group: 'APPROVAL', requiredChecklist: [{ code: 'STUDENT_APPROVAL', title: 'Student approved the institution shortlist' }] },
    { code: 'APPLICATIONS_SUBMITTED', name: 'Applications Submitted', group: 'PROCESSING' },
    { code: 'CONDITIONAL_OFFER', name: 'Conditional Offer Received', group: 'PROCESSING' },
    { code: 'CONDITIONS_FULFILLED', name: 'Conditions Fulfilled', group: 'PROCESSING' },
    { code: 'UNCONDITIONAL_OFFER', name: 'Unconditional Offer Received', group: 'PROCESSING' },
    { code: 'INSTITUTION_SELECTED', name: 'Institution Selected', group: 'PROCESSING' },
    { code: 'TUITION_DEPOSIT_PAID', name: 'Tuition Deposit Paid', group: 'PAYMENT', requiresPayment: true },
    { code: 'ENROLMENT_DOC_RECEIVED', name: 'Enrolment Document Received', group: 'DOCUMENTATION' },
    { code: 'VISA_CHECKLIST_GENERATED', name: 'Visa Checklist Generated', group: 'DOCUMENTATION' },
    { code: 'FINANCIAL_DOCS_REVIEWED', name: 'Financial Documents Reviewed', group: 'DOCUMENTATION', requiredChecklist: [{ code: 'FINANCIALS_REVIEWED', title: 'Financial capacity documents reviewed' }] },
    { code: 'VISA_APPLICATION_PREPARED', name: 'Visa Application Prepared', group: 'PROCESSING' },
    { code: 'QUALITY_REVIEW', name: 'Internal Quality Review', group: 'APPROVAL', requiresApproval: true },
    { code: 'VISA_SUBMITTED', name: 'Visa Submitted', group: 'PROCESSING' },
    { code: 'BIOMETRICS_MEDICAL_INTERVIEW', name: 'Biometrics, Medical or Interview', group: 'PROCESSING' },
    { code: 'VISA_DECISION', name: 'Visa Decision', group: 'PROCESSING' },
    { code: 'ACCOMMODATION_ARRANGED', name: 'Accommodation Arranged', group: 'BOOKING' },
    { code: 'INSURANCE_ARRANGED', name: 'Insurance Arranged', group: 'BOOKING' },
    { code: 'AIR_TICKET_ARRANGED', name: 'Air Ticket Arranged', group: 'BOOKING' },
    { code: 'PRE_DEPARTURE_BRIEFING', name: 'Pre-Departure Briefing', group: 'DELIVERY' },
    { code: 'STUDENT_ARRIVED', name: 'Student Arrived', group: 'DELIVERY' },
    { code: 'ENROLMENT_CONFIRMED', name: 'Enrolment Confirmed', group: 'DELIVERY' },
    { code: 'COMMISSION_TRACKED', name: 'Commission Receivable Tracked', group: 'AFTER_SALES' },
    { code: 'CASE_CLOSED', name: 'Case Closed', group: 'CLOSURE', isTerminal: true },
  ],
};

export const MANPOWER_TEMPLATE: WorkflowTemplateDefinition = {
  serviceTypeCode: 'MANPOWER',
  code: 'MANPOWER_STANDARD',
  name: 'Manpower / Recruitment — Standard',
  description: 'Employer verification to deployment and post-deployment support; no discriminatory automated selection',
  version: V,
  stages: [
    { code: 'EMPLOYER_LEAD_RECEIVED', name: 'Employer Lead Received', group: 'INTAKE', slaHours: 8, isInitial: true },
    { code: 'EMPLOYER_VERIFICATION', name: 'Employer Verification', group: 'QUALIFICATION', requiredChecklist: [{ code: 'EMPLOYER_VERIFIED', title: 'Employer legitimacy verified' }] },
    { code: 'DEMAND_DOCS_COLLECTED', name: 'Demand Documents Collected', group: 'DOCUMENTATION' },
    { code: 'JOB_ORDER_VERIFIED', name: 'Job Order Verified', group: 'DOCUMENTATION', requiredChecklist: [{ code: 'JOB_ORDER', title: 'Demand/job-order documents verified' }] },
    { code: 'REGULATORY_REVIEW', name: 'Regulatory Review', group: 'APPROVAL', requiresApproval: true },
    { code: 'VACANCY_APPROVED', name: 'Vacancy Approved', group: 'PROCESSING' },
    { code: 'VACANCY_PUBLISHED', name: 'Vacancy Published', group: 'PROCESSING' },
    { code: 'CANDIDATE_REGISTRATION', name: 'Candidate Registration', group: 'INTAKE' },
    { code: 'CANDIDATE_DOCS_COLLECTED', name: 'Candidate Documents Collected', group: 'DOCUMENTATION', requiredDocumentTypes: ['PASSPORT'] },
    { code: 'INITIAL_SCREENING', name: 'Initial Screening', group: 'QUALIFICATION' },
    { code: 'INTERVIEW_SCHEDULED', name: 'Interview Scheduled', group: 'PROCESSING' },
    { code: 'TRADE_TEST_SCHEDULED', name: 'Trade Test Scheduled', group: 'PROCESSING' },
    { code: 'EMPLOYER_INTERVIEW', name: 'Employer Interview', group: 'PROCESSING' },
    { code: 'CANDIDATE_SELECTED', name: 'Candidate Selected', group: 'PROCESSING' },
    { code: 'CONTRACT_ACCEPTED', name: 'Employment Contract Accepted', group: 'DOCUMENTATION', requiredChecklist: [{ code: 'CONTRACT_SIGNED', title: 'Contract signed with version preserved; fees disclosed transparently' }] },
    { code: 'MEDICAL_SCHEDULED', name: 'Medical Scheduled', group: 'PROCESSING' },
    { code: 'MEDICAL_RESULT', name: 'Medical Result Received', group: 'PROCESSING' },
    { code: 'POLICE_CLEARANCE', name: 'Police Clearance or Attestation', group: 'DOCUMENTATION' },
    { code: 'TRAINING_COMPLETED', name: 'Training Completed', group: 'PROCESSING' },
    { code: 'VISA_PROCESSING', name: 'Visa Processing', group: 'PROCESSING' },
    { code: 'VISA_ISSUED', name: 'Visa Issued', group: 'PROCESSING' },
    { code: 'GOVERNMENT_PROCESSING', name: 'Government and Regulatory Processing', group: 'PROCESSING' },
    { code: 'INSURANCE_WELFARE', name: 'Insurance and Welfare Processing', group: 'PROCESSING' },
    { code: 'FINAL_PAYMENT_REVIEW', name: 'Final Payment Review', group: 'PAYMENT', requiresPayment: true },
    { code: 'TICKET_ISSUED', name: 'Ticket Issued', group: 'BOOKING' },
    { code: 'PRE_DEPARTURE_BRIEFING', name: 'Pre-Departure Briefing', group: 'DELIVERY' },
    { code: 'WORKER_DEPLOYED', name: 'Worker Deployed', group: 'DELIVERY' },
    { code: 'EMPLOYER_HANDOVER', name: 'Employer Handover Confirmed', group: 'DELIVERY', requiredChecklist: [{ code: 'HANDOVER_CONFIRMED', title: 'Employer confirmed worker handover' }] },
    { code: 'PROBATION_FOLLOW_UP', name: 'Probation Follow-Up', group: 'AFTER_SALES' },
    { code: 'POST_DEPLOYMENT_SUPPORT', name: 'Post-Deployment Support', group: 'AFTER_SALES' },
    { code: 'FINANCIAL_RECONCILIATION', name: 'Financial Reconciliation', group: 'AFTER_SALES' },
    { code: 'CASE_CLOSED', name: 'Case Closed', group: 'CLOSURE', isTerminal: true },
  ],
};

export const CRUISE_TEMPLATE: WorkflowTemplateDefinition = {
  serviceTypeCode: 'CRUISE',
  code: 'CRUISE_STANDARD',
  name: 'Cruise — Standard',
  description: 'Enquiry to embarkation with cabin hold expiry and final-payment gates',
  version: V,
  stages: [
    { code: 'ENQUIRY_RECEIVED', name: 'Cruise Enquiry Received', group: 'INTAKE', slaHours: 4, isInitial: true },
    { code: 'REQUIREMENTS_COLLECTED', name: 'Travel Requirements Collected', group: 'INTAKE' },
    { code: 'SAILINGS_SEARCHED', name: 'Sailings Searched', group: 'PROCESSING' },
    { code: 'ITINERARY_COMPARED', name: 'Itinerary Compared', group: 'QUOTATION' },
    { code: 'CABIN_OPTIONS_COMPARED', name: 'Cabin Options Compared', group: 'QUOTATION' },
    { code: 'VISA_REQUIREMENTS_REVIEWED', name: 'Visa Requirements Reviewed', group: 'DOCUMENTATION' },
    { code: 'QUOTATION_SENT', name: 'Quotation Sent', group: 'QUOTATION', slaHours: 24 },
    { code: 'SAILING_CABIN_SELECTED', name: 'Sailing and Cabin Selected', group: 'QUOTATION' },
    { code: 'PASSENGER_INFO_COLLECTED', name: 'Passenger Information Collected', group: 'DOCUMENTATION', requiredChecklist: [{ code: 'NAME_VERIFICATION', title: 'Passenger names verified against passports' }] },
    { code: 'CABIN_HELD', name: 'Cabin Held', group: 'BOOKING' },
    { code: 'HOLD_EXPIRY_RECORDED', name: 'Hold Expiry Recorded', group: 'BOOKING', requiredChecklist: [{ code: 'HOLD_EXPIRY', title: 'Cabin hold expiry deadline recorded' }] },
    { code: 'DEPOSIT_RECEIVED', name: 'Deposit Received', group: 'PAYMENT', requiresPayment: true },
    { code: 'CABIN_CONFIRMED', name: 'Cabin Confirmed', group: 'BOOKING' },
    { code: 'TRAVEL_ARRANGED', name: 'Flights, Hotel and Transfer Arranged', group: 'BOOKING' },
    { code: 'INSURANCE_ARRANGED', name: 'Insurance Arranged', group: 'BOOKING' },
    { code: 'VISA_PROCESSING', name: 'Visa Processing', group: 'PROCESSING' },
    { code: 'FINAL_PAYMENT_REMINDER', name: 'Final Payment Reminder', group: 'PAYMENT', slaHours: 48 },
    { code: 'FINAL_PAYMENT_RECEIVED', name: 'Final Payment Received', group: 'PAYMENT', requiresPayment: true },
    { code: 'ONLINE_CHECKIN_COMPLETED', name: 'Online Check-In Completed', group: 'PROCESSING', requiredChecklist: [{ code: 'CHECKIN', title: 'Online check-in completed for all passengers' }] },
    { code: 'CRUISE_DOCS_GENERATED', name: 'Cruise Documents Generated', group: 'DELIVERY' },
    { code: 'BAGGAGE_TAGS_DELIVERED', name: 'Baggage Tags Delivered', group: 'DELIVERY' },
    { code: 'PRE_DEPARTURE_VERIFICATION', name: 'Pre-Departure Verification', group: 'DELIVERY' },
    { code: 'EMBARKATION', name: 'Embarkation', group: 'DELIVERY' },
    { code: 'SAILING_COMPLETED', name: 'Sailing Completed', group: 'DELIVERY' },
    { code: 'SUPPLIER_RECONCILIATION', name: 'Supplier Reconciliation', group: 'AFTER_SALES' },
    { code: 'CASE_CLOSED', name: 'Case Closed', group: 'CLOSURE', isTerminal: true },
  ],
};

export const EXTENDED_WORKFLOW_TEMPLATES: WorkflowTemplateDefinition[] = [
  INSURANCE_TEMPLATE,
  TRANSFER_TEMPLATE,
  UMRAH_TEMPLATE,
  HAJJ_TEMPLATE,
  MEDICAL_TOURISM_TEMPLATE,
  STUDENT_VISA_TEMPLATE,
  MANPOWER_TEMPLATE,
  CRUISE_TEMPLATE,
];
