export const ALL_COUNTRIES = [
  { name: 'Afghanistan', iso2: 'AF', iso3: 'AFG', dialCode: '+93', currencyCode: 'AFN', continent: 'Asia' },
  { name: 'Albania', iso2: 'AL', iso3: 'ALB', dialCode: '+355', currencyCode: 'ALL', continent: 'Europe' },
  { name: 'Algeria', iso2: 'DZ', iso3: 'DZA', dialCode: '+213', currencyCode: 'DZD', continent: 'Africa' },
  { name: 'Angola', iso2: 'AO', iso3: 'AGO', dialCode: '+244', currencyCode: 'AOA', continent: 'Africa' },
  { name: 'Argentina', iso2: 'AR', iso3: 'ARG', dialCode: '+54', currencyCode: 'ARS', continent: 'South America' },
  { name: 'Armenia', iso2: 'AM', iso3: 'ARM', dialCode: '+374', currencyCode: 'AMD', continent: 'Asia' },
  { name: 'Australia', iso2: 'AU', iso3: 'AUS', dialCode: '+61', currencyCode: 'AUD', continent: 'Oceania' },
  { name: 'Austria', iso2: 'AT', iso3: 'AUT', dialCode: '+43', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Azerbaijan', iso2: 'AZ', iso3: 'AZE', dialCode: '+994', currencyCode: 'AZN', continent: 'Asia' },
  { name: 'Bahrain', iso2: 'BH', iso3: 'BHR', dialCode: '+973', currencyCode: 'BHD', continent: 'Asia' },
  { name: 'Bangladesh', iso2: 'BD', iso3: 'BGD', dialCode: '+880', currencyCode: 'BDT', continent: 'Asia', nationalityLabel: 'Bangladeshi' },
  { name: 'Belarus', iso2: 'BY', iso3: 'BLR', dialCode: '+375', currencyCode: 'BYN', continent: 'Europe' },
  { name: 'Belgium', iso2: 'BE', iso3: 'BEL', dialCode: '+32', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Bhutan', iso2: 'BT', iso3: 'BTN', dialCode: '+975', currencyCode: 'BTN', continent: 'Asia' },
  { name: 'Bolivia', iso2: 'BO', iso3: 'BOL', dialCode: '+591', currencyCode: 'BOB', continent: 'South America' },
  { name: 'Bosnia', iso2: 'BA', iso3: 'BIH', dialCode: '+387', currencyCode: 'BAM', continent: 'Europe' },
  { name: 'Brazil', iso2: 'BR', iso3: 'BRA', dialCode: '+55', currencyCode: 'BRL', continent: 'South America' },
  { name: 'Brunei', iso2: 'BN', iso3: 'BRN', dialCode: '+673', currencyCode: 'BND', continent: 'Asia' },
  { name: 'Bulgaria', iso2: 'BG', iso3: 'BGR', dialCode: '+359', currencyCode: 'BGN', continent: 'Europe' },
  { name: 'Cambodia', iso2: 'KH', iso3: 'KHM', dialCode: '+855', currencyCode: 'KHR', continent: 'Asia' },
  { name: 'Cameroon', iso2: 'CM', iso3: 'CMR', dialCode: '+237', currencyCode: 'XAF', continent: 'Africa' },
  { name: 'Canada', iso2: 'CA', iso3: 'CAN', dialCode: '+1', currencyCode: 'CAD', continent: 'North America' },
  { name: 'Chile', iso2: 'CL', iso3: 'CHL', dialCode: '+56', currencyCode: 'CLP', continent: 'South America' },
  { name: 'China', iso2: 'CN', iso3: 'CHN', dialCode: '+86', currencyCode: 'CNY', continent: 'Asia' },
  { name: 'Colombia', iso2: 'CO', iso3: 'COL', dialCode: '+57', currencyCode: 'COP', continent: 'South America' },
  { name: 'Croatia', iso2: 'HR', iso3: 'HRV', dialCode: '+385', currencyCode: 'HRK', continent: 'Europe' },
  { name: 'Cuba', iso2: 'CU', iso3: 'CUB', dialCode: '+53', currencyCode: 'CUP', continent: 'North America' },
  { name: 'Cyprus', iso2: 'CY', iso3: 'CYP', dialCode: '+357', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Czech Republic', iso2: 'CZ', iso3: 'CZE', dialCode: '+420', currencyCode: 'CZK', continent: 'Europe' },
  { name: 'Denmark', iso2: 'DK', iso3: 'DNK', dialCode: '+45', currencyCode: 'DKK', continent: 'Europe' },
  { name: 'Ecuador', iso2: 'EC', iso3: 'ECU', dialCode: '+593', currencyCode: 'USD', continent: 'South America' },
  { name: 'Egypt', iso2: 'EG', iso3: 'EGY', dialCode: '+20', currencyCode: 'EGP', continent: 'Africa' },
  { name: 'Estonia', iso2: 'EE', iso3: 'EST', dialCode: '+372', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Ethiopia', iso2: 'ET', iso3: 'ETH', dialCode: '+251', currencyCode: 'ETB', continent: 'Africa' },
  { name: 'Fiji', iso2: 'FJ', iso3: 'FJI', dialCode: '+679', currencyCode: 'FJD', continent: 'Oceania' },
  { name: 'Finland', iso2: 'FI', iso3: 'FIN', dialCode: '+358', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'France', iso2: 'FR', iso3: 'FRA', dialCode: '+33', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Georgia', iso2: 'GE', iso3: 'GEO', dialCode: '+995', currencyCode: 'GEL', continent: 'Asia' },
  { name: 'Germany', iso2: 'DE', iso3: 'DEU', dialCode: '+49', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Ghana', iso2: 'GH', iso3: 'GHA', dialCode: '+233', currencyCode: 'GHS', continent: 'Africa' },
  { name: 'Greece', iso2: 'GR', iso3: 'GRC', dialCode: '+30', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Hong Kong', iso2: 'HK', iso3: 'HKG', dialCode: '+852', currencyCode: 'HKD', continent: 'Asia' },
  { name: 'Hungary', iso2: 'HU', iso3: 'HUN', dialCode: '+36', currencyCode: 'HUF', continent: 'Europe' },
  { name: 'Iceland', iso2: 'IS', iso3: 'ISL', dialCode: '+354', currencyCode: 'ISK', continent: 'Europe' },
  { name: 'India', iso2: 'IN', iso3: 'IND', dialCode: '+91', currencyCode: 'INR', continent: 'Asia', nationalityLabel: 'Indian' },
  { name: 'Indonesia', iso2: 'ID', iso3: 'IDN', dialCode: '+62', currencyCode: 'IDR', continent: 'Asia' },
  { name: 'Iran', iso2: 'IR', iso3: 'IRN', dialCode: '+98', currencyCode: 'IRR', continent: 'Asia' },
  { name: 'Iraq', iso2: 'IQ', iso3: 'IRQ', dialCode: '+964', currencyCode: 'IQD', continent: 'Asia' },
  { name: 'Ireland', iso2: 'IE', iso3: 'IRL', dialCode: '+353', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Israel', iso2: 'IL', iso3: 'ISR', dialCode: '+972', currencyCode: 'ILS', continent: 'Asia' },
  { name: 'Italy', iso2: 'IT', iso3: 'ITA', dialCode: '+39', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Japan', iso2: 'JP', iso3: 'JPN', dialCode: '+81', currencyCode: 'JPY', continent: 'Asia' },
  { name: 'Jordan', iso2: 'JO', iso3: 'JOR', dialCode: '+962', currencyCode: 'JOD', continent: 'Asia' },
  { name: 'Kazakhstan', iso2: 'KZ', iso3: 'KAZ', dialCode: '+7', currencyCode: 'KZT', continent: 'Asia' },
  { name: 'Kenya', iso2: 'KE', iso3: 'KEN', dialCode: '+254', currencyCode: 'KES', continent: 'Africa' },
  { name: 'Kuwait', iso2: 'KW', iso3: 'KWT', dialCode: '+965', currencyCode: 'KWD', continent: 'Asia' },
  { name: 'Kyrgyzstan', iso2: 'KG', iso3: 'KGZ', dialCode: '+996', currencyCode: 'KGS', continent: 'Asia' },
  { name: 'Laos', iso2: 'LA', iso3: 'LAO', dialCode: '+856', currencyCode: 'LAK', continent: 'Asia' },
  { name: 'Latvia', iso2: 'LV', iso3: 'LVA', dialCode: '+371', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Lebanon', iso2: 'LB', iso3: 'LBN', dialCode: '+961', currencyCode: 'LBP', continent: 'Asia' },
  { name: 'Libya', iso2: 'LY', iso3: 'LBY', dialCode: '+218', currencyCode: 'LYD', continent: 'Africa' },
  { name: 'Lithuania', iso2: 'LT', iso3: 'LTU', dialCode: '+370', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Luxembourg', iso2: 'LU', iso3: 'LUX', dialCode: '+352', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Malaysia', iso2: 'MY', iso3: 'MYS', dialCode: '+60', currencyCode: 'MYR', continent: 'Asia' },
  { name: 'Maldives', iso2: 'MV', iso3: 'MDV', dialCode: '+960', currencyCode: 'MVR', continent: 'Asia' },
  { name: 'Malta', iso2: 'MT', iso3: 'MLT', dialCode: '+356', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Mauritius', iso2: 'MU', iso3: 'MUS', dialCode: '+230', currencyCode: 'MUR', continent: 'Africa' },
  { name: 'Mexico', iso2: 'MX', iso3: 'MEX', dialCode: '+52', currencyCode: 'MXN', continent: 'North America' },
  { name: 'Mongolia', iso2: 'MN', iso3: 'MNG', dialCode: '+976', currencyCode: 'MNT', continent: 'Asia' },
  { name: 'Morocco', iso2: 'MA', iso3: 'MAR', dialCode: '+212', currencyCode: 'MAD', continent: 'Africa' },
  { name: 'Myanmar', iso2: 'MM', iso3: 'MMR', dialCode: '+95', currencyCode: 'MMK', continent: 'Asia' },
  { name: 'Nepal', iso2: 'NP', iso3: 'NPL', dialCode: '+977', currencyCode: 'NPR', continent: 'Asia' },
  { name: 'Netherlands', iso2: 'NL', iso3: 'NLD', dialCode: '+31', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'New Zealand', iso2: 'NZ', iso3: 'NZL', dialCode: '+64', currencyCode: 'NZD', continent: 'Oceania' },
  { name: 'Nigeria', iso2: 'NG', iso3: 'NGA', dialCode: '+234', currencyCode: 'NGN', continent: 'Africa' },
  { name: 'North Korea', iso2: 'KP', iso3: 'PRK', dialCode: '+850', currencyCode: 'KPW', continent: 'Asia' },
  { name: 'Norway', iso2: 'NO', iso3: 'NOR', dialCode: '+47', currencyCode: 'NOK', continent: 'Europe' },
  { name: 'Oman', iso2: 'OM', iso3: 'OMN', dialCode: '+968', currencyCode: 'OMR', continent: 'Asia' },
  { name: 'Pakistan', iso2: 'PK', iso3: 'PAK', dialCode: '+92', currencyCode: 'PKR', continent: 'Asia', nationalityLabel: 'Pakistani' },
  { name: 'Philippines', iso2: 'PH', iso3: 'PHL', dialCode: '+63', currencyCode: 'PHP', continent: 'Asia' },
  { name: 'Poland', iso2: 'PL', iso3: 'POL', dialCode: '+48', currencyCode: 'PLN', continent: 'Europe' },
  { name: 'Portugal', iso2: 'PT', iso3: 'PRT', dialCode: '+351', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Qatar', iso2: 'QA', iso3: 'QAT', dialCode: '+974', currencyCode: 'QAR', continent: 'Asia' },
  { name: 'Romania', iso2: 'RO', iso3: 'ROU', dialCode: '+40', currencyCode: 'RON', continent: 'Europe' },
  { name: 'Russia', iso2: 'RU', iso3: 'RUS', dialCode: '+7', currencyCode: 'RUB', continent: 'Europe' },
  { name: 'Rwanda', iso2: 'RW', iso3: 'RWA', dialCode: '+250', currencyCode: 'RWF', continent: 'Africa' },
  { name: 'Saudi Arabia', iso2: 'SA', iso3: 'SAU', dialCode: '+966', currencyCode: 'SAR', continent: 'Asia' },
  { name: 'Senegal', iso2: 'SN', iso3: 'SEN', dialCode: '+221', currencyCode: 'XOF', continent: 'Africa' },
  { name: 'Serbia', iso2: 'RS', iso3: 'SRB', dialCode: '+381', currencyCode: 'RSD', continent: 'Europe' },
  { name: 'Singapore', iso2: 'SG', iso3: 'SGP', dialCode: '+65', currencyCode: 'SGD', continent: 'Asia' },
  { name: 'Slovakia', iso2: 'SK', iso3: 'SVK', dialCode: '+421', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'South Africa', iso2: 'ZA', iso3: 'ZAF', dialCode: '+27', currencyCode: 'ZAR', continent: 'Africa' },
  { name: 'South Korea', iso2: 'KR', iso3: 'KOR', dialCode: '+82', currencyCode: 'KRW', continent: 'Asia' },
  { name: 'Spain', iso2: 'ES', iso3: 'ESP', dialCode: '+34', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Sri Lanka', iso2: 'LK', iso3: 'LKA', dialCode: '+94', currencyCode: 'LKR', continent: 'Asia' },
  { name: 'Sudan', iso2: 'SD', iso3: 'SDN', dialCode: '+249', currencyCode: 'SDG', continent: 'Africa' },
  { name: 'Sweden', iso2: 'SE', iso3: 'SWE', dialCode: '+46', currencyCode: 'SEK', continent: 'Europe' },
  { name: 'Switzerland', iso2: 'CH', iso3: 'CHE', dialCode: '+41', currencyCode: 'CHF', continent: 'Europe' },
  { name: 'Syria', iso2: 'SY', iso3: 'SYR', dialCode: '+963', currencyCode: 'SYP', continent: 'Asia' },
  { name: 'Taiwan', iso2: 'TW', iso3: 'TWN', dialCode: '+886', currencyCode: 'TWD', continent: 'Asia' },
  { name: 'Tajikistan', iso2: 'TJ', iso3: 'TJK', dialCode: '+992', currencyCode: 'TJS', continent: 'Asia' },
  { name: 'Tanzania', iso2: 'TZ', iso3: 'TZA', dialCode: '+255', currencyCode: 'TZS', continent: 'Africa' },
  { name: 'Thailand', iso2: 'TH', iso3: 'THA', dialCode: '+66', currencyCode: 'THB', continent: 'Asia' },
  { name: 'Tunisia', iso2: 'TN', iso3: 'TUN', dialCode: '+216', currencyCode: 'TND', continent: 'Africa' },
  { name: 'Turkey', iso2: 'TR', iso3: 'TUR', dialCode: '+90', currencyCode: 'TRY', continent: 'Europe' },
  { name: 'Turkmenistan', iso2: 'TM', iso3: 'TKM', dialCode: '+993', currencyCode: 'TMT', continent: 'Asia' },
  { name: 'UAE', iso2: 'AE', iso3: 'ARE', dialCode: '+971', currencyCode: 'AED', continent: 'Asia' },
  { name: 'Uganda', iso2: 'UG', iso3: 'UGA', dialCode: '+256', currencyCode: 'UGX', continent: 'Africa' },
  { name: 'Ukraine', iso2: 'UA', iso3: 'UKR', dialCode: '+380', currencyCode: 'UAH', continent: 'Europe' },
  { name: 'United Kingdom', iso2: 'GB', iso3: 'GBR', dialCode: '+44', currencyCode: 'GBP', continent: 'Europe' },
  { name: 'USA', iso2: 'US', iso3: 'USA', dialCode: '+1', currencyCode: 'USD', continent: 'North America' },
  { name: 'Uzbekistan', iso2: 'UZ', iso3: 'UZB', dialCode: '+998', currencyCode: 'UZS', continent: 'Asia' },
  { name: 'Venezuela', iso2: 'VE', iso3: 'VEN', dialCode: '+58', currencyCode: 'VES', continent: 'South America' },
  { name: 'Vietnam', iso2: 'VN', iso3: 'VNM', dialCode: '+84', currencyCode: 'VND', continent: 'Asia' },
  { name: 'Yemen', iso2: 'YE', iso3: 'YEM', dialCode: '+967', currencyCode: 'YER', continent: 'Asia' },
  { name: 'Zimbabwe', iso2: 'ZW', iso3: 'ZWE', dialCode: '+263', currencyCode: 'ZWL', continent: 'Africa' },
];

export const ALL_AIRLINES = [
  { iataCode: 'QR', icaoCode: 'QTR', name: 'Qatar Airways', countryIso2: 'QA' },
  { iataCode: 'EK', icaoCode: 'UAE', name: 'Emirates', countryIso2: 'AE' },
  { iataCode: 'EY', icaoCode: 'ETD', name: 'Etihad Airways', countryIso2: 'AE' },
  { iataCode: 'SV', icaoCode: 'SVA', name: 'Saudia', countryIso2: 'SA' },
  { iataCode: 'WY', icaoCode: 'OMA', name: 'Oman Air', countryIso2: 'OM' },
  { iataCode: 'GF', icaoCode: 'GFA', name: 'Gulf Air', countryIso2: 'BH' },
  { iataCode: 'KU', icaoCode: 'KAC', name: 'Kuwait Airways', countryIso2: 'KW' },
  { iataCode: 'TK', icaoCode: 'THY', name: 'Turkish Airlines', countryIso2: 'TR' },
  { iataCode: 'BG', icaoCode: 'BBC', name: 'Biman Bangladesh Airlines', countryIso2: 'BD' },
  { iataCode: 'SG', icaoCode: 'SEJ', name: 'SpiceJet', countryIso2: 'IN' },
  { iataCode: '6E', icaoCode: 'IGO', name: 'IndiGo', countryIso2: 'IN' },
  { iataCode: 'AI', icaoCode: 'AIC', name: 'Air India', countryIso2: 'IN' },
  { iataCode: 'UK', icaoCode: 'VTI', name: 'Vistara', countryIso2: 'IN' },
  { iataCode: 'MH', icaoCode: 'MAS', name: 'Malaysia Airlines', countryIso2: 'MY' },
  { iataCode: 'AK', icaoCode: 'AXM', name: 'AirAsia', countryIso2: 'MY' },
  { iataCode: 'OD', icaoCode: 'MXD', name: 'Malindo Air / Batik Air', countryIso2: 'MY' },
  { iataCode: 'SQ', icaoCode: 'SIA', name: 'Singapore Airlines', countryIso2: 'SG' },
  { iataCode: 'TR', icaoCode: 'TGW', name: 'Scoot', countryIso2: 'SG' },
  { iataCode: 'TG', icaoCode: 'THA', name: 'Thai Airways', countryIso2: 'TH' },
  { iataCode: 'CX', icaoCode: 'CPA', name: 'Cathay Pacific', countryIso2: 'HK' },
  { iataCode: 'BA', icaoCode: 'BAW', name: 'British Airways', countryIso2: 'GB' },
  { iataCode: 'LH', icaoCode: 'DLH', name: 'Lufthansa', countryIso2: 'DE' },
  { iataCode: 'AF', icaoCode: 'AFR', name: 'Air France', countryIso2: 'FR' },
  { iataCode: 'KL', icaoCode: 'KLM', name: 'KLM Royal Dutch Airlines', countryIso2: 'NL' },
  { iataCode: 'DL', icaoCode: 'DAL', name: 'Delta Air Lines', countryIso2: 'US' },
  { iataCode: 'UA', icaoCode: 'UAL', name: 'United Airlines', countryIso2: 'US' },
  { iataCode: 'AA', icaoCode: 'AAL', name: 'American Airlines', countryIso2: 'US' },
  { iataCode: 'B6', icaoCode: 'JBU', name: 'JetBlue Airways', countryIso2: 'US' },
  { iataCode: 'QF', icaoCode: 'QFA', name: 'Qantas', countryIso2: 'AU' },
  { iataCode: 'JQ', icaoCode: 'JST', name: 'Jetstar Airways', countryIso2: 'AU' },
  { iataCode: 'ET', icaoCode: 'ETH', name: 'Ethiopian Airlines', countryIso2: 'ET' },
  { iataCode: 'MS', icaoCode: 'MSR', name: 'EgyptAir', countryIso2: 'EG' },
  { iataCode: 'FZ', icaoCode: 'FDB', name: 'flydubai', countryIso2: 'AE' },
  { iataCode: 'G9', icaoCode: 'ABY', name: 'Air Arabia', countryIso2: 'AE' },
  { iataCode: 'J9', icaoCode: 'JZR', name: 'Jazeera Airways', countryIso2: 'KW' },
  { iataCode: 'OV', icaoCode: 'OMS', name: 'SalamAir', countryIso2: 'OM' },
  { iataCode: 'BS', icaoCode: 'UBG', name: 'US-Bangla Airlines', countryIso2: 'BD' },
  { iataCode: 'PR', icaoCode: 'PAL', name: 'Philippine Airlines', countryIso2: 'PH' },
  { iataCode: '5J', icaoCode: 'CEB', name: 'Cebu Pacific', countryIso2: 'PH' },
  { iataCode: 'GA', icaoCode: 'GIA', name: 'Garuda Indonesia', countryIso2: 'ID' },
  { iataCode: 'UL', icaoCode: 'ALK', name: 'SriLankan Airlines', countryIso2: 'LK' },
  { iataCode: 'RA', icaoCode: 'RNA', name: 'Nepal Airlines', countryIso2: 'NP' },
  { iataCode: 'KE', icaoCode: 'KAL', name: 'Korean Air', countryIso2: 'KR' },
  { iataCode: 'OZ', icaoCode: 'AAR', name: 'Asiana Airlines', countryIso2: 'KR' },
  { iataCode: 'CZ', icaoCode: 'CSN', name: 'China Southern', countryIso2: 'CN' },
  { iataCode: 'MU', icaoCode: 'CES', name: 'China Eastern', countryIso2: 'CN' },
  { iataCode: 'CA', icaoCode: 'CCA', name: 'Air China', countryIso2: 'CN' },
  { iataCode: '3U', icaoCode: 'CSC', name: 'Sichuan Airlines', countryIso2: 'CN' },
  { iataCode: 'VN', icaoCode: 'HVN', name: 'Vietnam Airlines', countryIso2: 'VN' },
  { iataCode: 'BR', icaoCode: 'EVA', name: 'EVA Air', countryIso2: 'TW' },
  { iataCode: 'CI', icaoCode: 'CAL', name: 'China Airlines', countryIso2: 'TW' },
  { iataCode: 'SU', icaoCode: 'AFL', name: 'Aeroflot', countryIso2: 'RU' },
  { iataCode: 'PC', icaoCode: 'PGT', name: 'Pegasus Airlines', countryIso2: 'TR' },
  { iataCode: 'W6', icaoCode: 'WZZ', name: 'Wizz Air', countryIso2: 'HU' },
  { iataCode: 'FR', icaoCode: 'RYR', name: 'Ryanair', countryIso2: 'IE' },
  { iataCode: 'U2', icaoCode: 'EZY', name: 'easyJet', countryIso2: 'GB' },
  { iataCode: 'ME', icaoCode: 'MEA', name: 'Middle East Airlines', countryIso2: 'LB' },
  { iataCode: 'RJ', icaoCode: 'RJA', name: 'Royal Jordanian', countryIso2: 'JO' },
  { iataCode: 'IR', icaoCode: 'IRA', name: 'Iran Air', countryIso2: 'IR' },
  { iataCode: 'PK', icaoCode: 'PIA', name: 'Pakistan International', countryIso2: 'PK' },
  { iataCode: 'WB', icaoCode: 'RWD', name: 'RwandAir', countryIso2: 'RW' },
  { iataCode: 'KQ', icaoCode: 'KQA', name: 'Kenya Airways', countryIso2: 'KE' },
  { iataCode: 'AT', icaoCode: 'RAM', name: 'Royal Air Maroc', countryIso2: 'MA' },
  { iataCode: 'AC', icaoCode: 'ACA', name: 'Air Canada', countryIso2: 'CA' },
  { iataCode: 'AZ', icaoCode: 'AZA', name: 'ITA Airways', countryIso2: 'IT' },
  { iataCode: 'AY', icaoCode: 'FIN', name: 'Finnair', countryIso2: 'FI' },
  { iataCode: 'SK', icaoCode: 'SAS', name: 'Scandinavian Airlines', countryIso2: 'SE' },
  { iataCode: 'OS', icaoCode: 'AUA', name: 'Austrian Airlines', countryIso2: 'AT' },
  { iataCode: 'LX', icaoCode: 'SWR', name: 'Swiss International Air Lines', countryIso2: 'CH' },
  { iataCode: 'TP', icaoCode: 'TAP', name: 'TAP Air Portugal', countryIso2: 'PT' },
  { iataCode: 'B2', icaoCode: 'BRU', name: 'Belavia', countryIso2: 'BY' },
  { iataCode: 'LO', icaoCode: 'LOT', name: 'LOT Polish Airlines', countryIso2: 'PL' },
  { iataCode: 'OK', icaoCode: 'CSA', name: 'Czech Airlines', countryIso2: 'CZ' },
  { iataCode: 'RO', icaoCode: 'ROT', name: 'TAROM', countryIso2: 'RO' },
  { iataCode: 'A3', icaoCode: 'AEE', name: 'Aegean Airlines', countryIso2: 'GR' },
  { iataCode: 'JU', icaoCode: 'ASL', name: 'Air Serbia', countryIso2: 'RS' },
  { iataCode: 'HY', icaoCode: 'UZB', name: 'Uzbekistan Airways', countryIso2: 'UZ' },
  { iataCode: 'KC', icaoCode: 'KZR', name: 'Air Astana', countryIso2: 'KZ' },
  { iataCode: 'OM', icaoCode: 'MGL', name: 'MIAT Mongolian Airlines', countryIso2: 'MN' },
  { iataCode: 'HH', icaoCode: 'TBN', name: 'Qanot Sharq', countryIso2: 'UZ' },
  { iataCode: 'NZ', icaoCode: 'ANZ', name: 'Air New Zealand', countryIso2: 'NZ' },
  { iataCode: 'LA', icaoCode: 'LAN', name: 'LATAM Airlines', countryIso2: 'CL' },
  { iataCode: 'JJ', icaoCode: 'TAM', name: 'LATAM Brasil', countryIso2: 'BR' },
  { iataCode: 'AM', icaoCode: 'AMX', name: 'Aeromexico', countryIso2: 'MX' },
  { iataCode: 'AV', icaoCode: 'AVA', name: 'Avianca', countryIso2: 'CO' },
  { iataCode: 'CM', icaoCode: 'CMP', name: 'Copa Airlines', countryIso2: 'PA' },
  { iataCode: 'AR', icaoCode: 'ARG', name: 'Aerolineas Argentinas', countryIso2: 'AR' },
  { iataCode: 'SA', icaoCode: 'SAA', name: 'South African Airways', countryIso2: 'ZA' },
  { iataCode: 'AH', icaoCode: 'DAH', name: 'Air Algerie', countryIso2: 'DZ' },
  { iataCode: 'TU', icaoCode: 'TAR', name: 'Tunisair', countryIso2: 'TN' },
  { iataCode: 'LY', icaoCode: 'ELY', name: 'El Al Israel Airlines', countryIso2: 'IL' },
  { iataCode: 'PS', icaoCode: 'AUI', name: 'Ukraine International', countryIso2: 'UA' },
  { iataCode: 'S7', icaoCode: 'SBI', name: 'S7 Airlines', countryIso2: 'RU' },
];

export const ALL_AIRPORTS = [
  { iataCode: 'DXB', name: 'Dubai International Airport', city: 'Dubai', countryIso2: 'AE', timezone: 'Asia/Dubai', latitude: 25.2532, longitude: 55.3657 },
  { iataCode: 'AUH', name: 'Abu Dhabi International Airport', city: 'Abu Dhabi', countryIso2: 'AE', timezone: 'Asia/Dubai', latitude: 24.4331, longitude: 54.6511 },
  { iataCode: 'SHJ', name: 'Sharjah International Airport', city: 'Sharjah', countryIso2: 'AE', timezone: 'Asia/Dubai', latitude: 25.3286, longitude: 55.5172 },
  { iataCode: 'DOH', name: 'Hamad International Airport', city: 'Doha', countryIso2: 'QA', timezone: 'Asia/Qatar', latitude: 25.2731, longitude: 51.6081 },
  { iataCode: 'JED', name: 'King Abdulaziz International Airport', city: 'Jeddah', countryIso2: 'SA', timezone: 'Asia/Riyadh', latitude: 21.6796, longitude: 39.1565 },
  { iataCode: 'RUH', name: 'King Khalid International Airport', city: 'Riyadh', countryIso2: 'SA', timezone: 'Asia/Riyadh', latitude: 24.9576, longitude: 46.6988 },
  { iataCode: 'MED', name: 'Prince Mohammad Bin Abdulaziz Airport', city: 'Medina', countryIso2: 'SA', timezone: 'Asia/Riyadh', latitude: 24.5534, longitude: 39.7051 },
  { iataCode: 'MCT', name: 'Muscat International Airport', city: 'Muscat', countryIso2: 'OM', timezone: 'Asia/Muscat', latitude: 23.5933, longitude: 58.2843 },
  { iataCode: 'KWI', name: 'Kuwait International Airport', city: 'Kuwait City', countryIso2: 'KW', timezone: 'Asia/Kuwait', latitude: 29.2266, longitude: 47.9689 },
  { iataCode: 'BAH', name: 'Bahrain International Airport', city: 'Manama', countryIso2: 'BH', timezone: 'Asia/Bahrain', latitude: 26.2708, longitude: 50.6336 },
  { iataCode: 'IST', name: 'Istanbul Airport', city: 'Istanbul', countryIso2: 'TR', timezone: 'Europe/Istanbul', latitude: 41.2608, longitude: 28.7418 },
  { iataCode: 'SAW', name: 'Sabiha Gokcen International Airport', city: 'Istanbul', countryIso2: 'TR', timezone: 'Europe/Istanbul', latitude: 40.8986, longitude: 29.3092 },
  { iataCode: 'DAC', name: 'Hazrat Shahjalal International Airport', city: 'Dhaka', countryIso2: 'BD', timezone: 'Asia/Dhaka', latitude: 23.8433, longitude: 90.3978 },
  { iataCode: 'CGP', name: 'Shah Amanat International Airport', city: 'Chittagong', countryIso2: 'BD', timezone: 'Asia/Dhaka', latitude: 22.2496, longitude: 91.8133 },
  { iataCode: 'ZYL', name: 'Osmani International Airport', city: 'Sylhet', countryIso2: 'BD', timezone: 'Asia/Dhaka', latitude: 24.9633, longitude: 91.8690 },
  { iataCode: 'CCU', name: 'Netaji Subhas Chandra Bose Airport', city: 'Kolkata', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 22.6547, longitude: 88.4467 },
  { iataCode: 'DEL', name: 'Indira Gandhi International Airport', city: 'Delhi', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 28.5562, longitude: 77.1000 },
  { iataCode: 'BOM', name: 'Chhatrapati Shivaji Maharaj Airport', city: 'Mumbai', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 19.0896, longitude: 72.8656 },
  { iataCode: 'MAA', name: 'Chennai International Airport', city: 'Chennai', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 12.9941, longitude: 80.1709 },
  { iataCode: 'BLR', name: 'Kempegowda International Airport', city: 'Bangalore', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 13.1986, longitude: 77.7066 },
  { iataCode: 'HYD', name: 'Rajiv Gandhi International Airport', city: 'Hyderabad', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 17.2313, longitude: 78.4299 },
  { iataCode: 'COK', name: 'Cochin International Airport', city: 'Kochi', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 10.1520, longitude: 76.4019 },
  { iataCode: 'AMD', name: 'Sardar Vallabhbhai Patel Airport', city: 'Ahmedabad', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 23.0772, longitude: 72.6347 },
  { iataCode: 'KUL', name: 'Kuala Lumpur International Airport', city: 'Kuala Lumpur', countryIso2: 'MY', timezone: 'Asia/Kuala_Lumpur', latitude: 2.7456, longitude: 101.7099 },
  { iataCode: 'SIN', name: 'Singapore Changi Airport', city: 'Singapore', countryIso2: 'SG', timezone: 'Asia/Singapore', latitude: 1.3644, longitude: 103.9915 },
  { iataCode: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok', countryIso2: 'TH', timezone: 'Asia/Bangkok', latitude: 13.6900, longitude: 100.7501 },
  { iataCode: 'DMK', name: 'Don Mueang International Airport', city: 'Bangkok', countryIso2: 'TH', timezone: 'Asia/Bangkok', latitude: 13.9125, longitude: 100.6067 },
  { iataCode: 'HKT', name: 'Phuket International Airport', city: 'Phuket', countryIso2: 'TH', timezone: 'Asia/Bangkok', latitude: 8.1132, longitude: 98.3169 },
  { iataCode: 'HKG', name: 'Hong Kong International Airport', city: 'Hong Kong', countryIso2: 'HK', timezone: 'Asia/Hong_Kong', latitude: 22.3080, longitude: 113.9185 },
  { iataCode: 'LHR', name: 'London Heathrow Airport', city: 'London', countryIso2: 'GB', timezone: 'Europe/London', latitude: 51.4700, longitude: -0.4543 },
  { iataCode: 'LGW', name: 'London Gatwick Airport', city: 'London', countryIso2: 'GB', timezone: 'Europe/London', latitude: 51.1481, longitude: -0.1903 },
  { iataCode: 'MAN', name: 'Manchester Airport', city: 'Manchester', countryIso2: 'GB', timezone: 'Europe/London', latitude: 53.3537, longitude: -2.2750 },
  { iataCode: 'BHX', name: 'Birmingham Airport', city: 'Birmingham', countryIso2: 'GB', timezone: 'Europe/London', latitude: 52.4539, longitude: -1.7480 },
  { iataCode: 'CDG', name: 'Charles de Gaulle Airport', city: 'Paris', countryIso2: 'FR', timezone: 'Europe/Paris', latitude: 49.0097, longitude: 2.5479 },
  { iataCode: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt', countryIso2: 'DE', timezone: 'Europe/Berlin', latitude: 50.0379, longitude: 8.5622 },
  { iataCode: 'MUC', name: 'Munich Airport', city: 'Munich', countryIso2: 'DE', timezone: 'Europe/Berlin', latitude: 48.3538, longitude: 11.7861 },
  { iataCode: 'AMS', name: 'Amsterdam Airport Schiphol', city: 'Amsterdam', countryIso2: 'NL', timezone: 'Europe/Amsterdam', latitude: 52.3105, longitude: 4.7683 },
  { iataCode: 'FCO', name: 'Leonardo da Vinci International Airport', city: 'Rome', countryIso2: 'IT', timezone: 'Europe/Rome', latitude: 41.8003, longitude: 12.2389 },
  { iataCode: 'MXP', name: 'Milan Malpensa Airport', city: 'Milan', countryIso2: 'IT', timezone: 'Europe/Rome', latitude: 45.6306, longitude: 8.7281 },
  { iataCode: 'MAD', name: 'Adolfo Suarez Madrid-Barajas Airport', city: 'Madrid', countryIso2: 'ES', timezone: 'Europe/Madrid', latitude: 40.4936, longitude: -3.5668 },
  { iataCode: 'BCN', name: 'Barcelona-El Prat Airport', city: 'Barcelona', countryIso2: 'ES', timezone: 'Europe/Madrid', latitude: 41.2969, longitude: 2.0783 },
  { iataCode: 'ZRH', name: 'Zurich Airport', city: 'Zurich', countryIso2: 'CH', timezone: 'Europe/Zurich', latitude: 47.4582, longitude: 8.5555 },
  { iataCode: 'GVA', name: 'Geneva Airport', city: 'Geneva', countryIso2: 'CH', timezone: 'Europe/Zurich', latitude: 46.2381, longitude: 6.1089 },
  { iataCode: 'JFK', name: 'John F Kennedy International Airport', city: 'New York', countryIso2: 'US', timezone: 'America/New_York', latitude: 40.6413, longitude: -73.7781 },
  { iataCode: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', countryIso2: 'US', timezone: 'America/Los_Angeles', latitude: 33.9416, longitude: -118.4085 },
  { iataCode: 'ORD', name: "O'Hare International Airport", city: 'Chicago', countryIso2: 'US', timezone: 'America/Chicago', latitude: 41.9742, longitude: -87.9073 },
  { iataCode: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco', countryIso2: 'US', timezone: 'America/Los_Angeles', latitude: 37.6213, longitude: -122.3790 },
  { iataCode: 'IAH', name: 'George Bush Intercontinental Airport', city: 'Houston', countryIso2: 'US', timezone: 'America/Chicago', latitude: 29.9902, longitude: -95.3368 },
  { iataCode: 'MIA', name: 'Miami International Airport', city: 'Miami', countryIso2: 'US', timezone: 'America/New_York', latitude: 25.7959, longitude: -80.2871 },
  { iataCode: 'YYZ', name: 'Toronto Pearson International Airport', city: 'Toronto', countryIso2: 'CA', timezone: 'America/Toronto', latitude: 43.6777, longitude: -79.6248 },
  { iataCode: 'YVR', name: 'Vancouver International Airport', city: 'Vancouver', countryIso2: 'CA', timezone: 'America/Vancouver', latitude: 49.1939, longitude: -123.1840 },
  { iataCode: 'YUL', name: 'Montreal-Trudeau International Airport', city: 'Montreal', countryIso2: 'CA', timezone: 'America/Toronto', latitude: 45.4577, longitude: -73.7499 },
  { iataCode: 'SYD', name: 'Sydney Kingsford Smith Airport', city: 'Sydney', countryIso2: 'AU', timezone: 'Australia/Sydney', latitude: -33.9399, longitude: 151.1753 },
  { iataCode: 'MEL', name: 'Melbourne Airport', city: 'Melbourne', countryIso2: 'AU', timezone: 'Australia/Melbourne', latitude: -37.6690, longitude: 144.8410 },
  { iataCode: 'BNE', name: 'Brisbane Airport', city: 'Brisbane', countryIso2: 'AU', timezone: 'Australia/Brisbane', latitude: -27.3842, longitude: 153.1175 },
  { iataCode: 'PER', name: 'Perth Airport', city: 'Perth', countryIso2: 'AU', timezone: 'Australia/Perth', latitude: -31.9403, longitude: 115.9674 },
  { iataCode: 'CAI', name: 'Cairo International Airport', city: 'Cairo', countryIso2: 'EG', timezone: 'Africa/Cairo', latitude: 30.1114, longitude: 31.4003 },
  { iataCode: 'NBO', name: 'Jomo Kenyatta International Airport', city: 'Nairobi', countryIso2: 'KE', timezone: 'Africa/Nairobi', latitude: -1.3192, longitude: 36.9273 },
  { iataCode: 'ADD', name: 'Bole International Airport', city: 'Addis Ababa', countryIso2: 'ET', timezone: 'Africa/Addis_Ababa', latitude: 8.9779, longitude: 38.7993 },
  { iataCode: 'CMN', name: 'Mohammed V International Airport', city: 'Casablanca', countryIso2: 'MA', timezone: 'Africa/Casablanca', latitude: 33.3675, longitude: -7.5892 },
  { iataCode: 'LOS', name: 'Murtala Muhammed International Airport', city: 'Lagos', countryIso2: 'NG', timezone: 'Africa/Lagos', latitude: 6.5774, longitude: 3.3210 },
  { iataCode: 'CPT', name: 'Cape Town International Airport', city: 'Cape Town', countryIso2: 'ZA', timezone: 'Africa/Johannesburg', latitude: -33.9648, longitude: 18.6017 },
  { iataCode: 'JNB', name: 'OR Tambo International Airport', city: 'Johannesburg', countryIso2: 'ZA', timezone: 'Africa/Johannesburg', latitude: -26.1392, longitude: 28.2460 },
  { iataCode: 'NRT', name: 'Narita International Airport', city: 'Tokyo', countryIso2: 'JP', timezone: 'Asia/Tokyo', latitude: 35.7719, longitude: 140.3925 },
  { iataCode: 'HND', name: 'Haneda Airport', city: 'Tokyo', countryIso2: 'JP', timezone: 'Asia/Tokyo', latitude: 35.5533, longitude: 139.7811 },
  { iataCode: 'KIX', name: 'Kansai International Airport', city: 'Osaka', countryIso2: 'JP', timezone: 'Asia/Tokyo', latitude: 34.4320, longitude: 135.2304 },
  { iataCode: 'ICN', name: 'Incheon International Airport', city: 'Seoul', countryIso2: 'KR', timezone: 'Asia/Seoul', latitude: 37.4602, longitude: 126.4407 },
  { iataCode: 'PEK', name: 'Beijing Capital International Airport', city: 'Beijing', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 40.0799, longitude: 116.6031 },
  { iataCode: 'PVG', name: 'Shanghai Pudong International Airport', city: 'Shanghai', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 31.1443, longitude: 121.8083 },
  { iataCode: 'CAN', name: 'Guangzhou Baiyun International Airport', city: 'Guangzhou', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 23.3925, longitude: 113.2988 },
  { iataCode: 'CGK', name: 'Soekarno-Hatta International Airport', city: 'Jakarta', countryIso2: 'ID', timezone: 'Asia/Jakarta', latitude: -6.1256, longitude: 106.6558 },
  { iataCode: 'DPS', name: 'Ngurah Rai International Airport', city: 'Bali', countryIso2: 'ID', timezone: 'Asia/Makassar', latitude: -8.7482, longitude: 115.1675 },
  { iataCode: 'MNL', name: 'Ninoy Aquino International Airport', city: 'Manila', countryIso2: 'PH', timezone: 'Asia/Manila', latitude: 14.5086, longitude: 121.0198 },
  { iataCode: 'SGN', name: 'Tan Son Nhat International Airport', city: 'Ho Chi Minh City', countryIso2: 'VN', timezone: 'Asia/Ho_Chi_Minh', latitude: 10.8188, longitude: 106.6520 },
  { iataCode: 'HAN', name: 'Noi Bai International Airport', city: 'Hanoi', countryIso2: 'VN', timezone: 'Asia/Ho_Chi_Minh', latitude: 21.2212, longitude: 105.8072 },
  { iataCode: 'RGN', name: 'Yangon International Airport', city: 'Yangon', countryIso2: 'MM', timezone: 'Asia/Yangon', latitude: 16.9073, longitude: 96.1332 },
  { iataCode: 'KTM', name: 'Tribhuvan International Airport', city: 'Kathmandu', countryIso2: 'NP', timezone: 'Asia/Kathmandu', latitude: 27.6966, longitude: 85.3591 },
  { iataCode: 'CMB', name: 'Bandaranaike International Airport', city: 'Colombo', countryIso2: 'LK', timezone: 'Asia/Colombo', latitude: 7.1808, longitude: 79.8841 },
  { iataCode: 'MLE', name: 'Velana International Airport', city: 'Male', countryIso2: 'MV', timezone: 'Indian/Maldives', latitude: 4.1918, longitude: 73.5291 },
  { iataCode: 'KBL', name: 'Kabul International Airport', city: 'Kabul', countryIso2: 'AF', timezone: 'Asia/Kabul', latitude: 34.5659, longitude: 69.2123 },
  { iataCode: 'AMM', name: 'Queen Alia International Airport', city: 'Amman', countryIso2: 'JO', timezone: 'Asia/Amman', latitude: 31.7226, longitude: 35.9932 },
  { iataCode: 'BEY', name: 'Beirut-Rafic Hariri International Airport', city: 'Beirut', countryIso2: 'LB', timezone: 'Asia/Beirut', latitude: 33.8209, longitude: 35.4884 },
  { iataCode: 'IKA', name: 'Imam Khomeini International Airport', city: 'Tehran', countryIso2: 'IR', timezone: 'Asia/Tehran', latitude: 35.4161, longitude: 51.1522 },
  { iataCode: 'ISB', name: 'Islamabad International Airport', city: 'Islamabad', countryIso2: 'PK', timezone: 'Asia/Karachi', latitude: 33.5607, longitude: 72.8517 },
  { iataCode: 'LHE', name: 'Allama Iqbal International Airport', city: 'Lahore', countryIso2: 'PK', timezone: 'Asia/Karachi', latitude: 31.5216, longitude: 74.4036 },
  { iataCode: 'KHI', name: 'Jinnah International Airport', city: 'Karachi', countryIso2: 'PK', timezone: 'Asia/Karachi', latitude: 24.9065, longitude: 67.1608 },
  { iataCode: 'GRU', name: 'Sao Paulo-Guarulhos International Airport', city: 'Sao Paulo', countryIso2: 'BR', timezone: 'America/Sao_Paulo', latitude: -23.4356, longitude: -46.4731 },
  { iataCode: 'EZE', name: 'Ministro Pistarini International Airport', city: 'Buenos Aires', countryIso2: 'AR', timezone: 'America/Argentina/Buenos_Aires', latitude: -34.8222, longitude: -58.5358 },
  { iataCode: 'MRU', name: 'Sir Seewoosagur Ramgoolam Airport', city: 'Port Louis', countryIso2: 'MU', timezone: 'Indian/Mauritius', latitude: -20.4302, longitude: 57.6836 },
  { iataCode: 'SEZ', name: 'Seychelles International Airport', city: 'Mahe', countryIso2: 'SC', timezone: 'Indian/Mahe', latitude: -4.6743, longitude: 55.5218 },
  { iataCode: 'AKL', name: 'Auckland Airport', city: 'Auckland', countryIso2: 'NZ', timezone: 'Pacific/Auckland', latitude: -37.0081, longitude: 174.7917 },
  { iataCode: 'VIE', name: 'Vienna International Airport', city: 'Vienna', countryIso2: 'AT', timezone: 'Europe/Vienna', latitude: 48.1102, longitude: 16.5697 },
  { iataCode: 'BRU', name: 'Brussels Airport', city: 'Brussels', countryIso2: 'BE', timezone: 'Europe/Brussels', latitude: 50.9014, longitude: 4.4844 },
  { iataCode: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', countryIso2: 'DK', timezone: 'Europe/Copenhagen', latitude: 55.6180, longitude: 12.6508 },
  { iataCode: 'HEL', name: 'Helsinki-Vantaa Airport', city: 'Helsinki', countryIso2: 'FI', timezone: 'Europe/Helsinki', latitude: 60.3172, longitude: 24.9633 },
  { iataCode: 'ATH', name: 'Athens International Airport', city: 'Athens', countryIso2: 'GR', timezone: 'Europe/Athens', latitude: 37.9364, longitude: 23.9445 },
  { iataCode: 'DUB', name: 'Dublin Airport', city: 'Dublin', countryIso2: 'IE', timezone: 'Europe/Dublin', latitude: 53.4213, longitude: -6.2701 },
  { iataCode: 'OSL', name: 'Oslo Gardermoen Airport', city: 'Oslo', countryIso2: 'NO', timezone: 'Europe/Oslo', latitude: 60.1939, longitude: 11.1004 },
  { iataCode: 'WAW', name: 'Warsaw Chopin Airport', city: 'Warsaw', countryIso2: 'PL', timezone: 'Europe/Warsaw', latitude: 52.1657, longitude: 20.9671 },
  { iataCode: 'LIS', name: 'Lisbon Airport', city: 'Lisbon', countryIso2: 'PT', timezone: 'Europe/Lisbon', latitude: 38.7813, longitude: -9.1359 },
  { iataCode: 'ARN', name: 'Stockholm Arlanda Airport', city: 'Stockholm', countryIso2: 'SE', timezone: 'Europe/Stockholm', latitude: 59.6519, longitude: 17.9186 },
  { iataCode: 'TLL', name: 'Tallinn Airport', city: 'Tallinn', countryIso2: 'EE', timezone: 'Europe/Tallinn', latitude: 59.4133, longitude: 24.8328 },
  { iataCode: 'RIX', name: 'Riga International Airport', city: 'Riga', countryIso2: 'LV', timezone: 'Europe/Riga', latitude: 56.9236, longitude: 23.9711 },
  { iataCode: 'TBS', name: 'Tbilisi International Airport', city: 'Tbilisi', countryIso2: 'GE', timezone: 'Asia/Tbilisi', latitude: 41.6692, longitude: 44.9547 },
  { iataCode: 'EVN', name: 'Zvartnots International Airport', city: 'Yerevan', countryIso2: 'AM', timezone: 'Asia/Yerevan', latitude: 40.1473, longitude: 44.3959 },
  { iataCode: 'ALA', name: 'Almaty International Airport', city: 'Almaty', countryIso2: 'KZ', timezone: 'Asia/Almaty', latitude: 43.3521, longitude: 77.0405 },
  { iataCode: 'TAS', name: 'Tashkent International Airport', city: 'Tashkent', countryIso2: 'UZ', timezone: 'Asia/Tashkent', latitude: 41.2579, longitude: 69.2812 },
  { iataCode: 'FRU', name: 'Manas International Airport', city: 'Bishkek', countryIso2: 'KG', timezone: 'Asia/Bishkek', latitude: 43.0613, longitude: 74.4776 },
  { iataCode: 'DYU', name: 'Dushanbe International Airport', city: 'Dushanbe', countryIso2: 'TJ', timezone: 'Asia/Dushanbe', latitude: 38.5433, longitude: 68.8250 },
  { iataCode: 'ASB', name: 'Ashgabat International Airport', city: 'Ashgabat', countryIso2: 'TM', timezone: 'Asia/Ashgabat', latitude: 37.9869, longitude: 58.3610 },
  { iataCode: 'GYD', name: 'Heydar Aliyev International Airport', city: 'Baku', countryIso2: 'AZ', timezone: 'Asia/Baku', latitude: 40.4675, longitude: 50.0467 },
  { iataCode: 'MSQ', name: 'Minsk National Airport', city: 'Minsk', countryIso2: 'BY', timezone: 'Europe/Minsk', latitude: 53.8825, longitude: 28.0307 },
  { iataCode: 'KBP', name: 'Boryspil International Airport', city: 'Kyiv', countryIso2: 'UA', timezone: 'Europe/Kyiv', latitude: 50.3450, longitude: 30.8947 },
];

export const CURRENCIES = [
  { code: 'USD', name: 'US Dollar', symbol: '$', decimalPlaces: 2 },
  { code: 'EUR', name: 'Euro', symbol: '€', decimalPlaces: 2 },
  { code: 'GBP', name: 'British Pound', symbol: '£', decimalPlaces: 2 },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', decimalPlaces: 0 },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', decimalPlaces: 2 },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', decimalPlaces: 2 },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', decimalPlaces: 2 },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', decimalPlaces: 2 },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', decimalPlaces: 2 },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', decimalPlaces: 2 },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', decimalPlaces: 2 },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', decimalPlaces: 2 },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', decimalPlaces: 2 },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', decimalPlaces: 3 },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', decimalPlaces: 3 },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', decimalPlaces: 3 },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', decimalPlaces: 2 },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', decimalPlaces: 2 },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', decimalPlaces: 2 },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', decimalPlaces: 0 },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', decimalPlaces: 0 },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', decimalPlaces: 2 },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', decimalPlaces: 2 },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', decimalPlaces: 2 },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', decimalPlaces: 2 },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', decimalPlaces: 2 },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', decimalPlaces: 2 },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', decimalPlaces: 2 },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'රු', decimalPlaces: 2 },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'रू', decimalPlaces: 2 },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', decimalPlaces: 2 },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', decimalPlaces: 2 },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', decimalPlaces: 0 },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', decimalPlaces: 2 },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', decimalPlaces: 2 },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', decimalPlaces: 2 },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD', decimalPlaces: 2 },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'DT', decimalPlaces: 3 },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'DA', decimalPlaces: 2 },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', decimalPlaces: 2 },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', decimalPlaces: 0 },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', decimalPlaces: 2 },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', decimalPlaces: 2 },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', decimalPlaces: 2 },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', decimalPlaces: 2 },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', decimalPlaces: 2 },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', decimalPlaces: 2 },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', decimalPlaces: 2 },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', decimalPlaces: 2 },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', decimalPlaces: 2 },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', decimalPlaces: 2 },
  { code: 'ISK', name: 'Icelandic Krona', symbol: 'kr', decimalPlaces: 0 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', decimalPlaces: 2 },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', decimalPlaces: 2 },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', decimalPlaces: 2 },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', decimalPlaces: 2 },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', decimalPlaces: 2 },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', decimalPlaces: 2 },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', decimalPlaces: 0 },
];
