export const MASTER_DATA_SEED = {
  categories: [
    { code: 'lead-status', name: 'Lead Status', module: 'CRM', sortOrder: 1 },
    { code: 'lead-priority', name: 'Lead Priority', module: 'CRM', sortOrder: 2 },
    { code: 'lead-source', name: 'Lead Source', module: 'CRM', sortOrder: 3 },
    { code: 'contact-method', name: 'Contact Method', module: 'CRM', sortOrder: 4 },
    { code: 'service-type', name: 'Service Type', module: 'OPERATIONS', sortOrder: 5 },
    { code: 'trip-type', name: 'Trip Type', module: 'OPERATIONS', sortOrder: 6 },
    { code: 'travel-category', name: 'Travel Category', module: 'OPERATIONS', sortOrder: 7 },
    { code: 'passenger-type', name: 'Passenger Type', module: 'OPERATIONS', sortOrder: 8 },
    { code: 'visa-type', name: 'Visa Type', module: 'OPERATIONS', sortOrder: 9 },
    { code: 'payment-method', name: 'Payment Method', module: 'FINANCE', sortOrder: 10 },
    { code: 'invoice-status', name: 'Invoice Status', module: 'FINANCE', sortOrder: 11 },
    { code: 'payment-status', name: 'Payment Status', module: 'FINANCE', sortOrder: 12 },
    { code: 'expense-category', name: 'Expense Category', module: 'FINANCE', sortOrder: 13 },
    { code: 'refund-reason', name: 'Refund Reason', module: 'FINANCE', sortOrder: 14 },
    { code: 'ticket-status', name: 'Ticket Status', module: 'OPERATIONS', sortOrder: 15 },
    { code: 'booking-status', name: 'Booking Status', module: 'OPERATIONS', sortOrder: 16 },
    { code: 'leave-type', name: 'Leave Type', module: 'HRM', sortOrder: 17 },
    { code: 'attendance-status', name: 'Attendance Status', module: 'HRM', sortOrder: 18 },
    { code: 'employee-status', name: 'Employee Status', module: 'HRM', sortOrder: 19 },
    { code: 'task-priority', name: 'Task Priority', module: 'SYSTEM', sortOrder: 20 },
    { code: 'task-status', name: 'Task Status', module: 'SYSTEM', sortOrder: 21 },
    { code: 'document-category', name: 'Document Category', module: 'SYSTEM', sortOrder: 22 },
    { code: 'client-type', name: 'Client Type', module: 'CRM', sortOrder: 23 },
    { code: 'client-status', name: 'Client Status', module: 'CRM', sortOrder: 24 },
    { code: 'quotation-status', name: 'Quotation Status', module: 'OPERATIONS', sortOrder: 25 },
    { code: 'follow-up-status', name: 'Follow-up Status', module: 'CRM', sortOrder: 26 },
    { code: 'follow-up-channel', name: 'Follow-up Channel', module: 'CRM', sortOrder: 27 },
    { code: 'follow-up-outcome', name: 'Follow-up Outcome', module: 'CRM', sortOrder: 28 },
  ],
  items: {
    'lead-status': [
      { code: 'NEW', name: 'New', color: '#3b82f6' },
      { code: 'CONTACTED', name: 'Contacted', color: '#6366f1' },
      { code: 'QUALIFIED', name: 'Qualified', color: '#8b5cf6' },
      { code: 'QUOTATION_SENT', name: 'Quotation Sent', color: '#f59e0b' },
      { code: 'NEGOTIATION', name: 'Negotiation', color: '#f97316' },
      { code: 'WON', name: 'Won', color: '#22c55e' },
      { code: 'LOST', name: 'Lost', color: '#ef4444' },
      { code: 'DUPLICATE', name: 'Duplicate', color: '#6b7280' },
      { code: 'SPAM', name: 'Spam', color: '#6b7280' },
    ],
    'lead-priority': [
      { code: 'LOW', name: 'Low', color: '#6b7280' },
      { code: 'MEDIUM', name: 'Medium', color: '#3b82f6' },
      { code: 'HIGH', name: 'High', color: '#f59e0b' },
      { code: 'URGENT', name: 'Urgent', color: '#ef4444' },
    ],
    'lead-source': [
      { code: 'WEBSITE', name: 'Website', icon: 'globe' },
      { code: 'REFERRAL', name: 'Referral', icon: 'users' },
      { code: 'WALK_IN', name: 'Walk-in', icon: 'door-open' },
      { code: 'PHONE', name: 'Phone', icon: 'phone' },
      { code: 'SOCIAL', name: 'Social Media', icon: 'share' },
      { code: 'PARTNER', name: 'Partner', icon: 'handshake' },
      { code: 'EMAIL', name: 'Email', icon: 'mail' },
      { code: 'EVENT', name: 'Event', icon: 'calendar' },
      { code: 'ADVERTISEMENT', name: 'Advertisement', icon: 'megaphone' },
      { code: 'OTHER', name: 'Other', icon: 'more-horizontal' },
    ],
    'contact-method': [
      { code: 'PHONE', name: 'Phone' },
      { code: 'EMAIL', name: 'Email' },
      { code: 'WHATSAPP', name: 'WhatsApp' },
      { code: 'SMS', name: 'SMS' },
      { code: 'FACEBOOK', name: 'Facebook' },
      { code: 'INSTAGRAM', name: 'Instagram' },
      { code: 'TELEGRAM', name: 'Telegram' },
      { code: 'VIBER', name: 'Viber' },
      { code: 'MEETING', name: 'In-Person Meeting' },
    ],
    'service-type': [
      { code: 'AIR_TICKET', name: 'Air Ticket', icon: 'plane' },
      { code: 'VISA', name: 'Visa Processing', icon: 'file-check' },
      { code: 'HOTEL', name: 'Hotel Booking', icon: 'building' },
      { code: 'TOUR', name: 'Tour Package', icon: 'map' },
      { code: 'INSURANCE', name: 'Travel Insurance', icon: 'shield' },
      { code: 'TRANSFER', name: 'Airport Transfer', icon: 'car' },
      { code: 'UMRAH', name: 'Umrah Package', icon: 'sun' },
      { code: 'HAJJ', name: 'Hajj Package', icon: 'star' },
      { code: 'MEDICAL_TOURISM', name: 'Medical Tourism', icon: 'heart' },
      { code: 'STUDENT_VISA', name: 'Student Visa', icon: 'graduation-cap' },
      { code: 'MANPOWER', name: 'Manpower / Recruitment', icon: 'briefcase' },
      { code: 'CRUISE', name: 'Cruise', icon: 'anchor' },
      { code: 'OTHER', name: 'Other', icon: 'more-horizontal' },
    ],
    'trip-type': [
      { code: 'ONE_WAY', name: 'One Way' },
      { code: 'ROUND_TRIP', name: 'Round Trip' },
      { code: 'MULTI_CITY', name: 'Multi-City' },
      { code: 'OPEN_JAW', name: 'Open Jaw' },
    ],
    'travel-category': [
      { code: 'DOMESTIC', name: 'Domestic' },
      { code: 'INTERNATIONAL', name: 'International' },
      { code: 'REGIONAL', name: 'Regional' },
      { code: 'LOCAL', name: 'Local' },
    ],
    'passenger-type': [
      { code: 'ADULT', name: 'Adult' },
      { code: 'CHILD', name: 'Child (2-11)' },
      { code: 'INFANT', name: 'Infant (0-2)' },
      { code: 'SENIOR', name: 'Senior Citizen' },
      { code: 'STUDENT', name: 'Student' },
    ],
    'visa-type': [
      { code: 'TOURIST', name: 'Tourist Visa' },
      { code: 'BUSINESS', name: 'Business Visa' },
      { code: 'STUDENT', name: 'Student Visa' },
      { code: 'WORK', name: 'Work Visa' },
      { code: 'TRANSIT', name: 'Transit Visa' },
      { code: 'UMRAH', name: 'Umrah Visa' },
      { code: 'HAJJ', name: 'Hajj Visa' },
      { code: 'MEDICAL', name: 'Medical Visa' },
      { code: 'DIPLOMATIC', name: 'Diplomatic Visa' },
    ],
    'payment-method': [
      { code: 'CASH', name: 'Cash', icon: 'banknote' },
      { code: 'BANK_TRANSFER', name: 'Bank Transfer', icon: 'building-bank' },
      { code: 'CREDIT_CARD', name: 'Credit Card', icon: 'credit-card' },
      { code: 'DEBIT_CARD', name: 'Debit Card', icon: 'credit-card' },
      { code: 'MOBILE_WALLET', name: 'Mobile Wallet', icon: 'smartphone' },
      { code: 'CHEQUE', name: 'Cheque', icon: 'file-text' },
      { code: 'ONLINE_PAYMENT', name: 'Online Payment Gateway', icon: 'globe' },
      { code: 'PAYPAL', name: 'PayPal', icon: 'dollar-sign' },
    ],
    'invoice-status': [
      { code: 'DRAFT', name: 'Draft', color: '#6b7280' },
      { code: 'SENT', name: 'Sent', color: '#3b82f6' },
      { code: 'PAID', name: 'Paid', color: '#22c55e' },
      { code: 'PARTIALLY_PAID', name: 'Partially Paid', color: '#f59e0b' },
      { code: 'OVERDUE', name: 'Overdue', color: '#ef4444' },
      { code: 'CANCELLED', name: 'Cancelled', color: '#6b7280' },
      { code: 'REFUNDED', name: 'Refunded', color: '#8b5cf6' },
    ],
    'payment-status': [
      { code: 'PENDING', name: 'Pending', color: '#f59e0b' },
      { code: 'COMPLETED', name: 'Completed', color: '#22c55e' },
      { code: 'FAILED', name: 'Failed', color: '#ef4444' },
      { code: 'REFUNDED', name: 'Refunded', color: '#8b5cf6' },
      { code: 'PARTIALLY_REFUNDED', name: 'Partially Refunded', color: '#f97316' },
    ],
    'expense-category': [
      { code: 'OFFICE_SUPPLIES', name: 'Office Supplies' },
      { code: 'TRAVEL', name: 'Travel' },
      { code: 'MEALS', name: 'Meals & Entertainment' },
      { code: 'UTILITIES', name: 'Utilities' },
      { code: 'RENT', name: 'Rent' },
      { code: 'SALARY', name: 'Salary & Wages' },
      { code: 'COMMISSION', name: 'Commission' },
      { code: 'MARKETING', name: 'Marketing & Advertising' },
      { code: 'SOFTWARE', name: 'Software & Subscriptions' },
      { code: 'TRAINING', name: 'Training & Development' },
      { code: 'MAINTENANCE', name: 'Repair & Maintenance' },
      { code: 'INSURANCE', name: 'Insurance' },
      { code: 'TAX', name: 'Taxes & Fees' },
      { code: 'OTHER', name: 'Other' },
    ],
    'refund-reason': [
      { code: 'CANCELLATION', name: 'Booking Cancellation' },
      { code: 'DUPLICATE', name: 'Duplicate Payment' },
      { code: 'OVERCHARGE', name: 'Overcharge' },
      { code: 'SERVICE_ISSUE', name: 'Service Issue' },
      { code: 'CUSTOMER_REQUEST', name: 'Customer Request' },
      { code: 'FRAUD', name: 'Fraud' },
      { code: 'ADJUSTMENT', name: 'Adjustment' },
      { code: 'OTHER', name: 'Other' },
    ],
    'booking-status': [
      { code: 'HELD', name: 'Held', color: '#6b7280' },
      { code: 'CONFIRMED', name: 'Confirmed', color: '#3b82f6' },
      { code: 'TICKETED', name: 'Ticketed', color: '#22c55e' },
      { code: 'CANCELLED', name: 'Cancelled', color: '#ef4444' },
      { code: 'REFUNDED', name: 'Refunded', color: '#8b5cf6' },
      { code: 'VOIDED', name: 'Voided', color: '#6b7280' },
    ],
    'ticket-status': [
      { code: 'PENDING', name: 'Pending', color: '#f59e0b' },
      { code: 'ISSUED', name: 'Issued', color: '#22c55e' },
      { code: 'VOIDED', name: 'Voided', color: '#ef4444' },
      { code: 'REFUNDED', name: 'Refunded', color: '#8b5cf6' },
      { code: 'REISSUED', name: 'Reissued', color: '#3b82f6' },
    ],
    'leave-type': [
      { code: 'SICK', name: 'Sick Leave', color: '#ef4444' },
      { code: 'ANNUAL', name: 'Annual Leave', color: '#22c55e' },
      { code: 'UNPAID', name: 'Unpaid Leave', color: '#6b7280' },
      { code: 'MATERNITY', name: 'Maternity Leave', color: '#ec4899' },
      { code: 'PATERNITY', name: 'Paternity Leave', color: '#3b82f6' },
      { code: 'EMERGENCY', name: 'Emergency Leave', color: '#f97316' },
      { code: 'BEREAVEMENT', name: 'Bereavement Leave', color: '#8b5cf6' },
      { code: 'OTHER', name: 'Other', color: '#6b7280' },
    ],
    'attendance-status': [
      { code: 'PRESENT', name: 'Present', color: '#22c55e' },
      { code: 'ABSENT', name: 'Absent', color: '#ef4444' },
      { code: 'LATE', name: 'Late', color: '#f59e0b' },
      { code: 'HALF_DAY', name: 'Half Day', color: '#3b82f6' },
      { code: 'HOLIDAY', name: 'Holiday', color: '#8b5cf6' },
      { code: 'REMOTE', name: 'Remote Work', color: '#6366f1' },
    ],
    'employee-status': [
      { code: 'ACTIVE', name: 'Active', color: '#22c55e' },
      { code: 'INACTIVE', name: 'Inactive', color: '#6b7280' },
      { code: 'TERMINATED', name: 'Terminated', color: '#ef4444' },
      { code: 'ON_LEAVE', name: 'On Leave', color: '#f59e0b' },
      { code: 'PROBATION', name: 'Probation', color: '#3b82f6' },
      { code: 'SUSPENDED', name: 'Suspended', color: '#f97316' },
    ],
    'task-priority': [
      { code: 'LOW', name: 'Low', color: '#6b7280' },
      { code: 'MEDIUM', name: 'Medium', color: '#3b82f6' },
      { code: 'HIGH', name: 'High', color: '#f59e0b' },
      { code: 'URGENT', name: 'Urgent', color: '#ef4444' },
    ],
    'task-status': [
      { code: 'TODO', name: 'To Do', color: '#6b7280' },
      { code: 'IN_PROGRESS', name: 'In Progress', color: '#3b82f6' },
      { code: 'COMPLETED', name: 'Completed', color: '#22c55e' },
      { code: 'CANCELLED', name: 'Cancelled', color: '#ef4444' },
      { code: 'ON_HOLD', name: 'On Hold', color: '#f59e0b' },
    ],
    'document-category': [
      { code: 'PASSPORT', name: 'Passport' },
      { code: 'NID', name: 'National ID' },
      { code: 'VISA', name: 'Visa Document' },
      { code: 'TICKET', name: 'E-Ticket' },
      { code: 'INVOICE', name: 'Invoice' },
      { code: 'RECEIPT', name: 'Receipt' },
      { code: 'QUOTATION', name: 'Quotation' },
      { code: 'EMPLOYEE', name: 'Employee Document' },
      { code: 'SUPPLIER_AGREEMENT', name: 'Supplier Agreement' },
      { code: 'AUDIT_EVIDENCE', name: 'Audit Evidence' },
      { code: 'OTHER', name: 'Other' },
    ],
    'client-type': [
      { code: 'PERSON', name: 'Individual', icon: 'user' },
      { code: 'COMPANY', name: 'Company', icon: 'building' },
      { code: 'GOVERNMENT', name: 'Government', icon: 'landmark' },
      { code: 'NGO', name: 'NGO / Non-Profit', icon: 'heart' },
    ],
    'client-status': [
      { code: 'ACTIVE', name: 'Active', color: '#22c55e' },
      { code: 'INACTIVE', name: 'Inactive', color: '#6b7280' },
      { code: 'BLOCKED', name: 'Blocked', color: '#ef4444' },
      { code: 'VIP', name: 'VIP', color: '#f59e0b' },
      { code: 'LEAD', name: 'Lead (not yet client)', color: '#3b82f6' },
    ],
    'quotation-status': [
      { code: 'DRAFT', name: 'Draft', color: '#6b7280' },
      { code: 'SENT', name: 'Sent', color: '#3b82f6' },
      { code: 'VIEWED', name: 'Viewed', color: '#6366f1' },
      { code: 'ACCEPTED', name: 'Accepted', color: '#22c55e' },
      { code: 'REJECTED', name: 'Rejected', color: '#ef4444' },
      { code: 'EXPIRED', name: 'Expired', color: '#f97316' },
      { code: 'CANCELLED', name: 'Cancelled', color: '#6b7280' },
    ],
    'follow-up-status': [
      { code: 'PENDING', name: 'Pending', color: '#f59e0b' },
      { code: 'COMPLETED', name: 'Completed', color: '#22c55e' },
      { code: 'CANCELLED', name: 'Cancelled', color: '#6b7280' },
      { code: 'MISSED', name: 'Missed', color: '#ef4444' },
      { code: 'RESCHEDULED', name: 'Rescheduled', color: '#3b82f6' },
    ],
    'follow-up-channel': [
      { code: 'PHONE', name: 'Phone Call', icon: 'phone' },
      { code: 'EMAIL', name: 'Email', icon: 'mail' },
      { code: 'WHATSAPP', name: 'WhatsApp', icon: 'message-circle' },
      { code: 'MEETING', name: 'In-Person Meeting', icon: 'users' },
      { code: 'SMS', name: 'SMS', icon: 'message-square' },
      { code: 'VIDEO_CALL', name: 'Video Call', icon: 'video' },
    ],
    'follow-up-outcome': [
      { code: 'INTERESTED', name: 'Interested' },
      { code: 'NOT_INTERESTED', name: 'Not Interested' },
      { code: 'CALL_BACK_LATER', name: 'Call Back Later' },
      { code: 'QUOTATION_REQUESTED', name: 'Quotation Requested' },
      { code: 'BOOKING_CONFIRMED', name: 'Booking Confirmed' },
      { code: 'NO_ANSWER', name: 'No Answer' },
      { code: 'WRONG_NUMBER', name: 'Wrong Number' },
      { code: 'FOLLOW_UP_NEEDED', name: 'Follow-up Needed' },
    ],
  },
} as const;
