export const MISSING_COUNTRIES = [
  { name: 'Andorra', iso2: 'AD', iso3: 'AND', dialCode: '+376', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Antigua and Barbuda', iso2: 'AG', iso3: 'ATG', dialCode: '+1268', currencyCode: 'XCD', continent: 'North America' },
  { name: 'Bahamas', iso2: 'BS', iso3: 'BHS', dialCode: '+1242', currencyCode: 'BSD', continent: 'North America' },
  { name: 'Barbados', iso2: 'BB', iso3: 'BRB', dialCode: '+1246', currencyCode: 'BBD', continent: 'North America' },
  { name: 'Belize', iso2: 'BZ', iso3: 'BLZ', dialCode: '+501', currencyCode: 'BZD', continent: 'North America' },
  { name: 'Benin', iso2: 'BJ', iso3: 'BEN', dialCode: '+229', currencyCode: 'XOF', continent: 'Africa' },
  { name: 'Botswana', iso2: 'BW', iso3: 'BWA', dialCode: '+267', currencyCode: 'BWP', continent: 'Africa' },
  { name: 'Burkina Faso', iso2: 'BF', iso3: 'BFA', dialCode: '+226', currencyCode: 'XOF', continent: 'Africa' },
  { name: 'Burundi', iso2: 'BI', iso3: 'BDI', dialCode: '+257', currencyCode: 'BIF', continent: 'Africa' },
  { name: 'Cape Verde', iso2: 'CV', iso3: 'CPV', dialCode: '+238', currencyCode: 'CVE', continent: 'Africa' },
  { name: 'Central African Republic', iso2: 'CF', iso3: 'CAF', dialCode: '+236', currencyCode: 'XAF', continent: 'Africa' },
  { name: 'Chad', iso2: 'TD', iso3: 'TCD', dialCode: '+235', currencyCode: 'XAF', continent: 'Africa' },
  { name: 'Comoros', iso2: 'KM', iso3: 'COM', dialCode: '+269', currencyCode: 'KMF', continent: 'Africa' },
  { name: 'Congo', iso2: 'CG', iso3: 'COG', dialCode: '+242', currencyCode: 'XAF', continent: 'Africa' },
  { name: 'Costa Rica', iso2: 'CR', iso3: 'CRI', dialCode: '+506', currencyCode: 'CRC', continent: 'North America' },
  { name: "Cote d'Ivoire", iso2: 'CI', iso3: 'CIV', dialCode: '+225', currencyCode: 'XOF', continent: 'Africa' },
  { name: 'Djibouti', iso2: 'DJ', iso3: 'DJI', dialCode: '+253', currencyCode: 'DJF', continent: 'Africa' },
  { name: 'Dominican Republic', iso2: 'DO', iso3: 'DOM', dialCode: '+1809', currencyCode: 'DOP', continent: 'North America' },
  { name: 'DR Congo', iso2: 'CD', iso3: 'COD', dialCode: '+243', currencyCode: 'CDF', continent: 'Africa' },
  { name: 'El Salvador', iso2: 'SV', iso3: 'SLV', dialCode: '+503', currencyCode: 'USD', continent: 'North America' },
  { name: 'Equatorial Guinea', iso2: 'GQ', iso3: 'GNQ', dialCode: '+240', currencyCode: 'XAF', continent: 'Africa' },
  { name: 'Eritrea', iso2: 'ER', iso3: 'ERI', dialCode: '+291', currencyCode: 'ERN', continent: 'Africa' },
  { name: 'Eswatini', iso2: 'SZ', iso3: 'SWZ', dialCode: '+268', currencyCode: 'SZL', continent: 'Africa' },
  { name: 'Gabon', iso2: 'GA', iso3: 'GAB', dialCode: '+241', currencyCode: 'XAF', continent: 'Africa' },
  { name: 'Gambia', iso2: 'GM', iso3: 'GMB', dialCode: '+220', currencyCode: 'GMD', continent: 'Africa' },
  { name: 'Guatemala', iso2: 'GT', iso3: 'GTM', dialCode: '+502', currencyCode: 'GTQ', continent: 'North America' },
  { name: 'Guinea', iso2: 'GN', iso3: 'GIN', dialCode: '+224', currencyCode: 'GNF', continent: 'Africa' },
  { name: 'Guinea-Bissau', iso2: 'GW', iso3: 'GNB', dialCode: '+245', currencyCode: 'XOF', continent: 'Africa' },
  { name: 'Guyana', iso2: 'GY', iso3: 'GUY', dialCode: '+592', currencyCode: 'GYD', continent: 'South America' },
  { name: 'Haiti', iso2: 'HT', iso3: 'HTI', dialCode: '+509', currencyCode: 'HTG', continent: 'North America' },
  { name: 'Honduras', iso2: 'HN', iso3: 'HND', dialCode: '+504', currencyCode: 'HNL', continent: 'North America' },
  { name: 'Jamaica', iso2: 'JM', iso3: 'JAM', dialCode: '+1876', currencyCode: 'JMD', continent: 'North America' },
  { name: 'Lesotho', iso2: 'LS', iso3: 'LSO', dialCode: '+266', currencyCode: 'LSL', continent: 'Africa' },
  { name: 'Liberia', iso2: 'LR', iso3: 'LBR', dialCode: '+231', currencyCode: 'LRD', continent: 'Africa' },
  { name: 'Liechtenstein', iso2: 'LI', iso3: 'LIE', dialCode: '+423', currencyCode: 'CHF', continent: 'Europe' },
  { name: 'Madagascar', iso2: 'MG', iso3: 'MDG', dialCode: '+261', currencyCode: 'MGA', continent: 'Africa' },
  { name: 'Malawi', iso2: 'MW', iso3: 'MWI', dialCode: '+265', currencyCode: 'MWK', continent: 'Africa' },
  { name: 'Mali', iso2: 'ML', iso3: 'MLI', dialCode: '+223', currencyCode: 'XOF', continent: 'Africa' },
  { name: 'Marshall Islands', iso2: 'MH', iso3: 'MHL', dialCode: '+692', currencyCode: 'USD', continent: 'Oceania' },
  { name: 'Mauritania', iso2: 'MR', iso3: 'MRT', dialCode: '+222', currencyCode: 'MRU', continent: 'Africa' },
  { name: 'Micronesia', iso2: 'FM', iso3: 'FSM', dialCode: '+691', currencyCode: 'USD', continent: 'Oceania' },
  { name: 'Moldova', iso2: 'MD', iso3: 'MDA', dialCode: '+373', currencyCode: 'MDL', continent: 'Europe' },
  { name: 'Monaco', iso2: 'MC', iso3: 'MCO', dialCode: '+377', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Montenegro', iso2: 'ME', iso3: 'MNE', dialCode: '+382', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Mozambique', iso2: 'MZ', iso3: 'MOZ', dialCode: '+258', currencyCode: 'MZN', continent: 'Africa' },
  { name: 'Namibia', iso2: 'NA', iso3: 'NAM', dialCode: '+264', currencyCode: 'NAD', continent: 'Africa' },
  { name: 'Nicaragua', iso2: 'NI', iso3: 'NIC', dialCode: '+505', currencyCode: 'NIO', continent: 'North America' },
  { name: 'Niger', iso2: 'NE', iso3: 'NER', dialCode: '+227', currencyCode: 'XOF', continent: 'Africa' },
  { name: 'North Macedonia', iso2: 'MK', iso3: 'MKD', dialCode: '+389', currencyCode: 'MKD', continent: 'Europe' },
  { name: 'Palau', iso2: 'PW', iso3: 'PLW', dialCode: '+680', currencyCode: 'USD', continent: 'Oceania' },
  { name: 'Palestine', iso2: 'PS', iso3: 'PSE', dialCode: '+970', currencyCode: 'ILS', continent: 'Asia' },
  { name: 'Panama', iso2: 'PA', iso3: 'PAN', dialCode: '+507', currencyCode: 'PAB', continent: 'North America' },
  { name: 'Papua New Guinea', iso2: 'PG', iso3: 'PNG', dialCode: '+675', currencyCode: 'PGK', continent: 'Oceania' },
  { name: 'Paraguay', iso2: 'PY', iso3: 'PRY', dialCode: '+595', currencyCode: 'PYG', continent: 'South America' },
  { name: 'Peru', iso2: 'PE', iso3: 'PER', dialCode: '+51', currencyCode: 'PEN', continent: 'South America' },
  { name: 'Samoa', iso2: 'WS', iso3: 'WSM', dialCode: '+685', currencyCode: 'WST', continent: 'Oceania' },
  { name: 'San Marino', iso2: 'SM', iso3: 'SMR', dialCode: '+378', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Sao Tome and Principe', iso2: 'ST', iso3: 'STP', dialCode: '+239', currencyCode: 'STN', continent: 'Africa' },
  { name: 'Sierra Leone', iso2: 'SL', iso3: 'SLE', dialCode: '+232', currencyCode: 'SLL', continent: 'Africa' },
  { name: 'Slovenia', iso2: 'SI', iso3: 'SVN', dialCode: '+386', currencyCode: 'EUR', continent: 'Europe' },
  { name: 'Solomon Islands', iso2: 'SB', iso3: 'SLB', dialCode: '+677', currencyCode: 'SBD', continent: 'Oceania' },
  { name: 'Somalia', iso2: 'SO', iso3: 'SOM', dialCode: '+252', currencyCode: 'SOS', continent: 'Africa' },
  { name: 'South Sudan', iso2: 'SS', iso3: 'SSD', dialCode: '+211', currencyCode: 'SSP', continent: 'Africa' },
  { name: 'Suriname', iso2: 'SR', iso3: 'SUR', dialCode: '+597', currencyCode: 'SRD', continent: 'South America' },
  { name: 'Timor-Leste', iso2: 'TL', iso3: 'TLS', dialCode: '+670', currencyCode: 'USD', continent: 'Asia' },
  { name: 'Togo', iso2: 'TG', iso3: 'TGO', dialCode: '+228', currencyCode: 'XOF', continent: 'Africa' },
  { name: 'Tonga', iso2: 'TO', iso3: 'TON', dialCode: '+676', currencyCode: 'TOP', continent: 'Oceania' },
  { name: 'Trinidad and Tobago', iso2: 'TT', iso3: 'TTO', dialCode: '+1868', currencyCode: 'TTD', continent: 'North America' },
  { name: 'Tuvalu', iso2: 'TV', iso3: 'TUV', dialCode: '+688', currencyCode: 'AUD', continent: 'Oceania' },
  { name: 'Uruguay', iso2: 'UY', iso3: 'URY', dialCode: '+598', currencyCode: 'UYU', continent: 'South America' },
  { name: 'Vanuatu', iso2: 'VU', iso3: 'VUT', dialCode: '+678', currencyCode: 'VUV', continent: 'Oceania' },
  { name: 'Zambia', iso2: 'ZM', iso3: 'ZMB', dialCode: '+260', currencyCode: 'ZMW', continent: 'Africa' },
];

export const MORE_AIRLINES = [
  { iataCode: 'IB', icaoCode: 'IBE', name: 'Iberia', countryIso2: 'ES' },
  { iataCode: 'VY', icaoCode: 'VLG', name: 'Vueling', countryIso2: 'ES' },
  { iataCode: 'UX', icaoCode: 'AEA', name: 'Air Europa', countryIso2: 'ES' },
  { iataCode: 'EI', icaoCode: 'EIN', name: 'Aer Lingus', countryIso2: 'IE' },
  { iataCode: 'VS', icaoCode: 'VIR', name: 'Virgin Atlantic', countryIso2: 'GB' },
  { iataCode: 'SN', icaoCode: 'BEL', name: 'Brussels Airlines', countryIso2: 'BE' },
  { iataCode: 'EW', icaoCode: 'EWG', name: 'Eurowings', countryIso2: 'DE' },
  { iataCode: '4U', icaoCode: 'GWI', name: 'Germanwings', countryIso2: 'DE' },
  { iataCode: 'DY', icaoCode: 'NAX', name: 'Norwegian Air Shuttle', countryIso2: 'NO' },
  { iataCode: 'WF', icaoCode: 'WIF', name: 'Wideroe', countryIso2: 'NO' },
  { iataCode: 'BT', icaoCode: 'BTI', name: 'airBaltic', countryIso2: 'LV' },
  { iataCode: 'FI', icaoCode: 'ICE', name: 'Icelandair', countryIso2: 'IS' },
  { iataCode: 'OG', icaoCode: 'FPO', name: 'PLAY', countryIso2: 'IS' },
  { iataCode: 'KM', icaoCode: 'AMC', name: 'Air Malta', countryIso2: 'MT' },
  { iataCode: 'AE', icaoCode: 'MDA', name: 'Mandarin Airlines', countryIso2: 'TW' },
  { iataCode: 'HX', icaoCode: 'CRK', name: 'Hong Kong Airlines', countryIso2: 'HK' },
  { iataCode: 'UO', icaoCode: 'HKE', name: 'HK Express', countryIso2: 'HK' },
  { iataCode: 'MM', icaoCode: 'APJ', name: 'Peach Aviation', countryIso2: 'JP' },
  { iataCode: 'GK', icaoCode: 'JJP', name: 'Jetstar Japan', countryIso2: 'JP' },
  { iataCode: '7C', icaoCode: 'JJA', name: 'Jeju Air', countryIso2: 'KR' },
  { iataCode: 'LJ', icaoCode: 'JNA', name: 'Jin Air', countryIso2: 'KR' },
  { iataCode: 'TW', icaoCode: 'TWB', name: 'Tway Air', countryIso2: 'KR' },
  { iataCode: 'BX', icaoCode: 'ABL', name: 'Air Busan', countryIso2: 'KR' },
  { iataCode: 'ZE', icaoCode: 'ESR', name: 'Eastar Jet', countryIso2: 'KR' },
  { iataCode: 'RS', icaoCode: 'ASV', name: 'Air Seoul', countryIso2: 'KR' },
  { iataCode: 'SC', icaoCode: 'CDG', name: 'Shandong Airlines', countryIso2: 'CN' },
  { iataCode: 'ZH', icaoCode: 'CSZ', name: 'Shenzhen Airlines', countryIso2: 'CN' },
  { iataCode: 'MF', icaoCode: 'CXA', name: 'Xiamen Airlines', countryIso2: 'CN' },
  { iataCode: 'HU', icaoCode: 'CHH', name: 'Hainan Airlines', countryIso2: 'CN' },
  { iataCode: 'HO', icaoCode: 'DKH', name: 'Juneyao Air', countryIso2: 'CN' },
  { iataCode: 'FM', icaoCode: 'CSH', name: 'Shanghai Airlines', countryIso2: 'CN' },
  { iataCode: 'GS', icaoCode: 'GCR', name: 'Tianjin Airlines', countryIso2: 'CN' },
  { iataCode: '8L', icaoCode: 'LKE', name: 'Lucky Air', countryIso2: 'CN' },
  { iataCode: 'VJ', icaoCode: 'VJC', name: 'VietJet Air', countryIso2: 'VN' },
  { iataCode: 'QH', icaoCode: 'BAV', name: 'Bamboo Airways', countryIso2: 'VN' },
  { iataCode: 'BL', icaoCode: 'PIC', name: 'Pacific Airlines', countryIso2: 'VN' },
  { iataCode: 'DD', icaoCode: 'NOK', name: 'Nok Air', countryIso2: 'TH' },
  { iataCode: 'FD', icaoCode: 'AIQ', name: 'Thai AirAsia', countryIso2: 'TH' },
  { iataCode: 'SL', icaoCode: 'TLM', name: 'Thai Lion Air', countryIso2: 'TH' },
  { iataCode: 'WE', icaoCode: 'THD', name: 'Thai Smile', countryIso2: 'TH' },
  { iataCode: 'PG', icaoCode: 'BKP', name: 'Bangkok Airways', countryIso2: 'TH' },
  { iataCode: 'QG', icaoCode: 'CTV', name: 'Citilink', countryIso2: 'ID' },
  { iataCode: 'JT', icaoCode: 'LNI', name: 'Lion Air', countryIso2: 'ID' },
  { iataCode: 'ID', icaoCode: 'BTK', name: 'Batik Air Indonesia', countryIso2: 'ID' },
  { iataCode: 'IW', icaoCode: 'WON', name: 'Wings Air', countryIso2: 'ID' },
  { iataCode: 'Z2', icaoCode: 'APG', name: 'AirAsia Philippines', countryIso2: 'PH' },
  { iataCode: 'DG', icaoCode: 'SRQ', name: 'Cebgo', countryIso2: 'PH' },
  { iataCode: '8M', icaoCode: 'MMA', name: 'Myanmar Airways International', countryIso2: 'MM' },
  { iataCode: 'K6', icaoCode: 'KHV', name: 'Cambodia Angkor Air', countryIso2: 'KH' },
  { iataCode: 'QV', icaoCode: 'LAO', name: 'Lao Airlines', countryIso2: 'LA' },
  { iataCode: 'RQ', icaoCode: 'KAM', name: 'Kam Air', countryIso2: 'AF' },
  { iataCode: 'YA', icaoCode: 'CDQ', name: 'Ariana Afghan Airlines', countryIso2: 'AF' },
  { iataCode: 'G8', icaoCode: 'GOW', name: 'Go First', countryIso2: 'IN' },
  { iataCode: 'QP', icaoCode: 'AKJ', name: 'Akasa Air', countryIso2: 'IN' },
  { iataCode: 'IX', icaoCode: 'AXB', name: 'Air India Express', countryIso2: 'IN' },
  { iataCode: 'I5', icaoCode: 'IAD', name: 'AIX Connect', countryIso2: 'IN' },
  { iataCode: '2T', icaoCode: 'TFL', name: 'TruJet', countryIso2: 'IN' },
  { iataCode: 'NL', icaoCode: 'SAI', name: 'Shaheen Air', countryIso2: 'PK' },
  { iataCode: 'ER', icaoCode: 'SEP', name: 'Serene Air', countryIso2: 'PK' },
  { iataCode: 'PF', icaoCode: 'SIF', name: 'Air Sial', countryIso2: 'PK' },
  { iataCode: 'EP', icaoCode: 'IRC', name: 'Iran Aseman Airlines', countryIso2: 'IR' },
  { iataCode: 'W5', icaoCode: 'IRM', name: 'Mahan Air', countryIso2: 'IR' },
  { iataCode: 'QB', icaoCode: 'QSM', name: 'Qeshm Air', countryIso2: 'IR' },
  { iataCode: 'NP', icaoCode: 'NIA', name: 'Nile Air', countryIso2: 'EG' },
  { iataCode: 'SM', icaoCode: 'MSC', name: 'Air Cairo', countryIso2: 'EG' },
  { iataCode: 'XY', icaoCode: 'KNE', name: 'Flynas', countryIso2: 'SA' },
  { iataCode: 'F3', icaoCode: 'FAD', name: 'Flyadeal', countryIso2: 'SA' },
  { iataCode: 'XY', icaoCode: 'KNE', name: 'flynas', countryIso2: 'SA' },
  { iataCode: '3L', icaoCode: 'JTN', name: 'Air Arabia Abu Dhabi', countryIso2: 'AE' },
  { iataCode: 'NO', icaoCode: 'NOS', name: 'Neos', countryIso2: 'IT' },
  { iataCode: 'IG', icaoCode: 'ISS', name: 'Air Italy', countryIso2: 'IT' },
  { iataCode: 'XQ', icaoCode: 'SXS', name: 'SunExpress', countryIso2: 'TR' },
  { iataCode: 'KK', icaoCode: 'KKK', name: 'AtlasGlobal', countryIso2: 'TR' },
  { iataCode: 'VF', icaoCode: 'TKJ', name: 'AJet', countryIso2: 'TR' },
  { iataCode: 'XC', icaoCode: 'CAI', name: 'Corendon Airlines', countryIso2: 'TR' },
  { iataCode: '8Q', icaoCode: 'OHY', name: 'Onur Air', countryIso2: 'TR' },
  { iataCode: 'FB', icaoCode: 'LZB', name: 'Bulgaria Air', countryIso2: 'BG' },
  { iataCode: 'OU', icaoCode: 'CTN', name: 'Croatia Airlines', countryIso2: 'HR' },
  { iataCode: 'JP', icaoCode: 'ADR', name: 'Adria Airways', countryIso2: 'SI' },
  { iataCode: 'YM', icaoCode: 'MGX', name: 'Montenegro Airlines', countryIso2: 'ME' },
  { iataCode: 'B7', icaoCode: 'UIA', name: 'Uni Air', countryIso2: 'TW' },
  { iataCode: 'IT', icaoCode: 'TTW', name: 'Tigerair Taiwan', countryIso2: 'TW' },
  { iataCode: '8C', icaoCode: 'ATN', name: 'Air Transport International', countryIso2: 'US' },
  { iataCode: 'HA', icaoCode: 'HAL', name: 'Hawaiian Airlines', countryIso2: 'US' },
  { iataCode: 'AS', icaoCode: 'ASA', name: 'Alaska Airlines', countryIso2: 'US' },
  { iataCode: 'NK', icaoCode: 'NKS', name: 'Spirit Airlines', countryIso2: 'US' },
  { iataCode: 'F9', icaoCode: 'FFT', name: 'Frontier Airlines', countryIso2: 'US' },
  { iataCode: 'WS', icaoCode: 'WJA', name: 'WestJet', countryIso2: 'CA' },
  { iataCode: 'PD', icaoCode: 'POE', name: 'Porter Airlines', countryIso2: 'CA' },
  { iataCode: 'TS', icaoCode: 'TSC', name: 'Air Transat', countryIso2: 'CA' },
  { iataCode: '4O', icaoCode: 'AIJ', name: 'Interjet', countryIso2: 'MX' },
  { iataCode: 'Y4', icaoCode: 'VOI', name: 'Volaris', countryIso2: 'MX' },
  { iataCode: 'VB', icaoCode: 'VIV', name: 'VivaAerobus', countryIso2: 'MX' },
  { iataCode: 'P5', icaoCode: 'RPB', name: 'Wingo', countryIso2: 'CO' },
  { iataCode: 'H2', icaoCode: 'SKU', name: 'Sky Airline', countryIso2: 'CL' },
  { iataCode: 'OB', icaoCode: 'BOV', name: 'Boliviana de Aviacion', countryIso2: 'BO' },
  { iataCode: 'ZP', icaoCode: 'AZP', name: 'Paranair', countryIso2: 'PY' },
  { iataCode: '2Z', icaoCode: 'PTB', name: 'Passaredo', countryIso2: 'BR' },
  { iataCode: 'AD', icaoCode: 'AZU', name: 'Azul Brazilian Airlines', countryIso2: 'BR' },
  { iataCode: 'G3', icaoCode: 'GLO', name: 'GOL Linhas Aereas', countryIso2: 'BR' },
  { iataCode: 'H1', icaoCode: 'HHI', name: 'Hahn Air', countryIso2: 'DE' },
  { iataCode: 'TZ', icaoCode: 'TVJ', name: 'Thai VietJet Air', countryIso2: 'TH' },
  { iataCode: 'JU', icaoCode: 'ASL', name: 'Air Serbia', countryIso2: 'RS' },
  { iataCode: 'FA', icaoCode: 'SFR', name: 'FlySafair', countryIso2: 'ZA' },
  { iataCode: '4Z', icaoCode: 'LNK', name: 'Airlink', countryIso2: 'ZA' },
  { iataCode: 'GE', icaoCode: 'TNA', name: 'TransAsia Airways', countryIso2: 'TW' },
];

export const MORE_AIRPORTS = [
  { iataCode: 'MNL', name: 'Ninoy Aquino International Airport', city: 'Manila', countryIso2: 'PH', timezone: 'Asia/Manila', latitude: 14.5086, longitude: 121.0198 },
  { iataCode: 'CEB', name: 'Mactan-Cebu International Airport', city: 'Cebu', countryIso2: 'PH', timezone: 'Asia/Manila', latitude: 10.3075, longitude: 123.9794 },
  { iataCode: 'CRK', name: 'Clark International Airport', city: 'Angeles', countryIso2: 'PH', timezone: 'Asia/Manila', latitude: 15.1860, longitude: 120.5603 },
  { iataCode: 'SZX', name: 'Shenzhen Baoan Airport', city: 'Shenzhen', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 22.6393, longitude: 113.8107 },
  { iataCode: 'CTU', name: 'Chengdu Shuangliu Airport', city: 'Chengdu', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 30.5785, longitude: 103.9471 },
  { iataCode: 'CKG', name: 'Chongqing Jiangbei Airport', city: 'Chongqing', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 29.7192, longitude: 106.6417 },
  { iataCode: 'WUH', name: 'Wuhan Tianhe Airport', city: 'Wuhan', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 30.7838, longitude: 114.2081 },
  { iataCode: 'XMN', name: 'Xiamen Gaoqi Airport', city: 'Xiamen', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 24.5440, longitude: 118.1277 },
  { iataCode: 'URC', name: 'Urumqi Diwopu Airport', city: 'Urumqi', countryIso2: 'CN', timezone: 'Asia/Urumqi', latitude: 43.9071, longitude: 87.4742 },
  { iataCode: 'TNA', name: 'Jinan Yaoqiang Airport', city: 'Jinan', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 36.8572, longitude: 117.2160 },
  { iataCode: 'TAO', name: 'Qingdao Liuting Airport', city: 'Qingdao', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 36.2661, longitude: 120.3822 },
  { iataCode: 'HAK', name: 'Haikou Meilan Airport', city: 'Haikou', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 19.9349, longitude: 110.4590 },
  { iataCode: 'SYX', name: 'Sanya Phoenix Airport', city: 'Sanya', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 18.3029, longitude: 109.4122 },
  { iataCode: 'KMG', name: 'Kunming Changshui Airport', city: 'Kunming', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 25.1019, longitude: 102.9290 },
  { iataCode: 'PNH', name: 'Phnom Penh International Airport', city: 'Phnom Penh', countryIso2: 'KH', timezone: 'Asia/Phnom_Penh', latitude: 11.5466, longitude: 104.8441 },
  { iataCode: 'REP', name: 'Siem Reap International Airport', city: 'Siem Reap', countryIso2: 'KH', timezone: 'Asia/Phnom_Penh', latitude: 13.4107, longitude: 103.8129 },
  { iataCode: 'VTE', name: 'Wattay International Airport', city: 'Vientiane', countryIso2: 'LA', timezone: 'Asia/Vientiane', latitude: 17.9883, longitude: 102.5633 },
  { iataCode: 'LPQ', name: 'Luang Prabang Airport', city: 'Luang Prabang', countryIso2: 'LA', timezone: 'Asia/Vientiane', latitude: 19.8973, longitude: 102.1608 },
  { iataCode: 'UBN', name: 'Chinggis Khaan Airport', city: 'Ulaanbaatar', countryIso2: 'MN', timezone: 'Asia/Ulaanbaatar', latitude: 47.6430, longitude: 106.8198 },
  { iataCode: 'FUK', name: 'Fukuoka Airport', city: 'Fukuoka', countryIso2: 'JP', timezone: 'Asia/Tokyo', latitude: 33.5859, longitude: 130.4507 },
  { iataCode: 'CTS', name: 'New Chitose Airport', city: 'Sapporo', countryIso2: 'JP', timezone: 'Asia/Tokyo', latitude: 42.7752, longitude: 141.6923 },
  { iataCode: 'NGO', name: 'Chubu Centrair Airport', city: 'Nagoya', countryIso2: 'JP', timezone: 'Asia/Tokyo', latitude: 34.8584, longitude: 136.8054 },
  { iataCode: 'OKA', name: 'Naha Airport', city: 'Okinawa', countryIso2: 'JP', timezone: 'Asia/Tokyo', latitude: 26.1958, longitude: 127.6459 },
  { iataCode: 'ITM', name: 'Osaka Itami Airport', city: 'Osaka', countryIso2: 'JP', timezone: 'Asia/Tokyo', latitude: 34.7855, longitude: 135.4382 },
  { iataCode: 'PUS', name: 'Gimhae International Airport', city: 'Busan', countryIso2: 'KR', timezone: 'Asia/Seoul', latitude: 35.1795, longitude: 128.9382 },
  { iataCode: 'CJU', name: 'Jeju International Airport', city: 'Jeju', countryIso2: 'KR', timezone: 'Asia/Seoul', latitude: 33.5113, longitude: 126.4930 },
  { iataCode: 'TPE', name: 'Taiwan Taoyuan International Airport', city: 'Taipei', countryIso2: 'TW', timezone: 'Asia/Taipei', latitude: 25.0777, longitude: 121.2328 },
  { iataCode: 'KHH', name: 'Kaohsiung International Airport', city: 'Kaohsiung', countryIso2: 'TW', timezone: 'Asia/Taipei', latitude: 22.5771, longitude: 120.3500 },
  { iataCode: 'DMK', name: 'Don Mueang International Airport', city: 'Bangkok', countryIso2: 'TH', timezone: 'Asia/Bangkok', latitude: 13.9125, longitude: 100.6067 },
  { iataCode: 'CNX', name: 'Chiang Mai International Airport', city: 'Chiang Mai', countryIso2: 'TH', timezone: 'Asia/Bangkok', latitude: 18.7668, longitude: 98.9626 },
  { iataCode: 'KBV', name: 'Krabi International Airport', city: 'Krabi', countryIso2: 'TH', timezone: 'Asia/Bangkok', latitude: 8.0990, longitude: 98.9862 },
  { iataCode: 'USM', name: 'Samui Airport', city: 'Koh Samui', countryIso2: 'TH', timezone: 'Asia/Bangkok', latitude: 9.5478, longitude: 100.0622 },
  { iataCode: 'SUB', name: 'Juanda International Airport', city: 'Surabaya', countryIso2: 'ID', timezone: 'Asia/Jakarta', latitude: -7.3798, longitude: 112.7868 },
  { iataCode: 'UPG', name: 'Sultan Hasanuddin Airport', city: 'Makassar', countryIso2: 'ID', timezone: 'Asia/Makassar', latitude: -5.0616, longitude: 119.5540 },
  { iataCode: 'LOP', name: 'Lombok International Airport', city: 'Praya', countryIso2: 'ID', timezone: 'Asia/Makassar', latitude: -8.7573, longitude: 116.2767 },
  { iataCode: 'MDC', name: 'Sam Ratulangi Airport', city: 'Manado', countryIso2: 'ID', timezone: 'Asia/Makassar', latitude: 1.5492, longitude: 124.9260 },
  { iataCode: 'BWN', name: 'Brunei International Airport', city: 'Bandar Seri Begawan', countryIso2: 'BN', timezone: 'Asia/Brunei', latitude: 4.9442, longitude: 114.9284 },
  { iataCode: 'MDL', name: 'Mandalay International Airport', city: 'Mandalay', countryIso2: 'MM', timezone: 'Asia/Yangon', latitude: 21.7022, longitude: 95.9779 },
  { iataCode: 'DAD', name: 'Da Nang International Airport', city: 'Da Nang', countryIso2: 'VN', timezone: 'Asia/Ho_Chi_Minh', latitude: 16.0439, longitude: 108.1994 },
  { iataCode: 'CXR', name: 'Cam Ranh International Airport', city: 'Nha Trang', countryIso2: 'VN', timezone: 'Asia/Ho_Chi_Minh', latitude: 11.9982, longitude: 109.2194 },
  { iataCode: 'PEN', name: 'Penang International Airport', city: 'Penang', countryIso2: 'MY', timezone: 'Asia/Kuala_Lumpur', latitude: 5.2971, longitude: 100.2769 },
  { iataCode: 'BKI', name: 'Kota Kinabalu Airport', city: 'Kota Kinabalu', countryIso2: 'MY', timezone: 'Asia/Kuching', latitude: 5.9372, longitude: 116.0512 },
  { iataCode: 'KCH', name: 'Kuching International Airport', city: 'Kuching', countryIso2: 'MY', timezone: 'Asia/Kuching', latitude: 1.4877, longitude: 110.3467 },
  { iataCode: 'ADL', name: 'Adelaide Airport', city: 'Adelaide', countryIso2: 'AU', timezone: 'Australia/Adelaide', latitude: -34.9440, longitude: 138.5306 },
  { iataCode: 'OOL', name: 'Gold Coast Airport', city: 'Gold Coast', countryIso2: 'AU', timezone: 'Australia/Brisbane', latitude: -28.1644, longitude: 153.5047 },
  { iataCode: 'CNS', name: 'Cairns Airport', city: 'Cairns', countryIso2: 'AU', timezone: 'Australia/Brisbane', latitude: -16.8858, longitude: 145.7553 },
  { iataCode: 'DRW', name: 'Darwin International Airport', city: 'Darwin', countryIso2: 'AU', timezone: 'Australia/Darwin', latitude: -12.4147, longitude: 130.8767 },
  { iataCode: 'CHC', name: 'Christchurch Airport', city: 'Christchurch', countryIso2: 'NZ', timezone: 'Pacific/Auckland', latitude: -43.4894, longitude: 172.5344 },
  { iataCode: 'WLG', name: 'Wellington Airport', city: 'Wellington', countryIso2: 'NZ', timezone: 'Pacific/Auckland', latitude: -41.3272, longitude: 174.8053 },
  { iataCode: 'NAN', name: 'Nadi International Airport', city: 'Nadi', countryIso2: 'FJ', timezone: 'Pacific/Fiji', latitude: -17.7554, longitude: 177.4434 },
  { iataCode: 'SUV', name: 'Nausori International Airport', city: 'Suva', countryIso2: 'FJ', timezone: 'Pacific/Fiji', latitude: -18.0433, longitude: 178.5592 },
  { iataCode: 'EDI', name: 'Edinburgh Airport', city: 'Edinburgh', countryIso2: 'GB', timezone: 'Europe/London', latitude: 55.9500, longitude: -3.3725 },
  { iataCode: 'GLA', name: 'Glasgow Airport', city: 'Glasgow', countryIso2: 'GB', timezone: 'Europe/London', latitude: 55.8719, longitude: -4.4331 },
  { iataCode: 'BFS', name: 'Belfast International Airport', city: 'Belfast', countryIso2: 'GB', timezone: 'Europe/London', latitude: 54.6575, longitude: -6.2158 },
  { iataCode: 'NCE', name: 'Nice Cote dAzur Airport', city: 'Nice', countryIso2: 'FR', timezone: 'Europe/Paris', latitude: 43.6584, longitude: 7.2159 },
  { iataCode: 'LYS', name: 'Lyon-Saint Exupery Airport', city: 'Lyon', countryIso2: 'FR', timezone: 'Europe/Paris', latitude: 45.7256, longitude: 5.0811 },
  { iataCode: 'MRS', name: 'Marseille Provence Airport', city: 'Marseille', countryIso2: 'FR', timezone: 'Europe/Paris', latitude: 43.4393, longitude: 5.2214 },
  { iataCode: 'ORY', name: 'Paris Orly Airport', city: 'Paris', countryIso2: 'FR', timezone: 'Europe/Paris', latitude: 48.7262, longitude: 2.3652 },
  { iataCode: 'TXL', name: 'Berlin Brandenburg Airport', city: 'Berlin', countryIso2: 'DE', timezone: 'Europe/Berlin', latitude: 52.3667, longitude: 13.5033 },
  { iataCode: 'HAM', name: 'Hamburg Airport', city: 'Hamburg', countryIso2: 'DE', timezone: 'Europe/Berlin', latitude: 53.6304, longitude: 9.9882 },
  { iataCode: 'DUS', name: 'Dusseldorf Airport', city: 'Dusseldorf', countryIso2: 'DE', timezone: 'Europe/Berlin', latitude: 51.2895, longitude: 6.7668 },
  { iataCode: 'STR', name: 'Stuttgart Airport', city: 'Stuttgart', countryIso2: 'DE', timezone: 'Europe/Berlin', latitude: 48.6899, longitude: 9.2220 },
  { iataCode: 'NAP', name: 'Naples International Airport', city: 'Naples', countryIso2: 'IT', timezone: 'Europe/Rome', latitude: 40.8860, longitude: 14.2908 },
  { iataCode: 'BLQ', name: 'Bologna Guglielmo Marconi Airport', city: 'Bologna', countryIso2: 'IT', timezone: 'Europe/Rome', latitude: 44.5354, longitude: 11.2887 },
  { iataCode: 'VCE', name: 'Venice Marco Polo Airport', city: 'Venice', countryIso2: 'IT', timezone: 'Europe/Rome', latitude: 45.5053, longitude: 12.3519 },
  { iataCode: 'PMI', name: 'Palma de Mallorca Airport', city: 'Palma', countryIso2: 'ES', timezone: 'Europe/Madrid', latitude: 39.5517, longitude: 2.7388 },
  { iataCode: 'AGP', name: 'Malaga-Costa del Sol Airport', city: 'Malaga', countryIso2: 'ES', timezone: 'Europe/Madrid', latitude: 36.6749, longitude: -4.4991 },
  { iataCode: 'ALC', name: 'Alicante-Elche Airport', city: 'Alicante', countryIso2: 'ES', timezone: 'Europe/Madrid', latitude: 38.2822, longitude: -0.5582 },
  { iataCode: 'OPO', name: 'Francisco Sa Carneiro Airport', city: 'Porto', countryIso2: 'PT', timezone: 'Europe/Lisbon', latitude: 41.2481, longitude: -8.6814 },
  { iataCode: 'SOF', name: 'Sofia Airport', city: 'Sofia', countryIso2: 'BG', timezone: 'Europe/Sofia', latitude: 42.6952, longitude: 23.4062 },
  { iataCode: 'BEG', name: 'Belgrade Nikola Tesla Airport', city: 'Belgrade', countryIso2: 'RS', timezone: 'Europe/Belgrade', latitude: 44.8184, longitude: 20.3091 },
  { iataCode: 'OTP', name: 'Henri Coanda International Airport', city: 'Bucharest', countryIso2: 'RO', timezone: 'Europe/Bucharest', latitude: 44.5711, longitude: 26.0850 },
  { iataCode: 'PRG', name: 'Vaclav Havel Airport Prague', city: 'Prague', countryIso2: 'CZ', timezone: 'Europe/Prague', latitude: 50.1008, longitude: 14.2600 },
  { iataCode: 'BUD', name: 'Budapest Ferenc Liszt Airport', city: 'Budapest', countryIso2: 'HU', timezone: 'Europe/Budapest', latitude: 47.4298, longitude: 19.2611 },
  { iataCode: 'ZAG', name: 'Zagreb Airport', city: 'Zagreb', countryIso2: 'HR', timezone: 'Europe/Zagreb', latitude: 45.7432, longitude: 16.0688 },
  { iataCode: 'LCA', name: 'Larnaca International Airport', city: 'Larnaca', countryIso2: 'CY', timezone: 'Asia/Nicosia', latitude: 34.8751, longitude: 33.6249 },
  { iataCode: 'MLA', name: 'Malta International Airport', city: 'Valletta', countryIso2: 'MT', timezone: 'Europe/Malta', latitude: 35.8575, longitude: 14.4775 },
  { iataCode: 'LED', name: 'Pulkovo Airport', city: 'Saint Petersburg', countryIso2: 'RU', timezone: 'Europe/Moscow', latitude: 59.8003, longitude: 30.2625 },
  { iataCode: 'VKO', name: 'Vnukovo International Airport', city: 'Moscow', countryIso2: 'RU', timezone: 'Europe/Moscow', latitude: 55.5915, longitude: 37.2615 },
  { iataCode: 'DME', name: 'Domodedovo Airport', city: 'Moscow', countryIso2: 'RU', timezone: 'Europe/Moscow', latitude: 55.4086, longitude: 37.9063 },
  { iataCode: 'TLV', name: 'Ben Gurion Airport', city: 'Tel Aviv', countryIso2: 'IL', timezone: 'Asia/Jerusalem', latitude: 32.0114, longitude: 34.8867 },
  { iataCode: 'LAD', name: 'Quatro de Fevereiro Airport', city: 'Luanda', countryIso2: 'AO', timezone: 'Africa/Lagos', latitude: -8.8584, longitude: 13.2312 },
  { iataCode: 'TIP', name: 'Tripoli International Airport', city: 'Tripoli', countryIso2: 'LY', timezone: 'Africa/Tripoli', latitude: 32.6635, longitude: 13.1590 },
  { iataCode: 'TUN', name: 'Tunis-Carthage Airport', city: 'Tunis', countryIso2: 'TN', timezone: 'Africa/Tunis', latitude: 36.8510, longitude: 10.2272 },
  { iataCode: 'ALG', name: 'Houari Boumediene Airport', city: 'Algiers', countryIso2: 'DZ', timezone: 'Africa/Algiers', latitude: 36.6910, longitude: 3.2154 },
  { iataCode: 'SSH', name: 'Sharm El Sheikh Airport', city: 'Sharm El Sheikh', countryIso2: 'EG', timezone: 'Africa/Cairo', latitude: 27.9773, longitude: 34.3950 },
  { iataCode: 'HRG', name: 'Hurghada International Airport', city: 'Hurghada', countryIso2: 'EG', timezone: 'Africa/Cairo', latitude: 27.1783, longitude: 33.7994 },
  { iataCode: 'DAR', name: 'Julius Nyerere Airport', city: 'Dar es Salaam', countryIso2: 'TZ', timezone: 'Africa/Dar_es_Salaam', latitude: -6.8781, longitude: 39.2026 },
  { iataCode: 'ZNZ', name: 'Abeid Amani Karume Airport', city: 'Zanzibar', countryIso2: 'TZ', timezone: 'Africa/Dar_es_Salaam', latitude: -6.2220, longitude: 39.2249 },
  { iataCode: 'EBB', name: 'Entebbe International Airport', city: 'Entebbe', countryIso2: 'UG', timezone: 'Africa/Kampala', latitude: 0.0424, longitude: 32.4435 },
  { iataCode: 'JRO', name: 'Kilimanjaro International Airport', city: 'Arusha', countryIso2: 'TZ', timezone: 'Africa/Dar_es_Salaam', latitude: -3.4294, longitude: 37.0745 },
  { iataCode: 'ACC', name: 'Kotoka International Airport', city: 'Accra', countryIso2: 'GH', timezone: 'Africa/Accra', latitude: 5.6052, longitude: -0.1668 },
  { iataCode: 'ABV', name: 'Nnamdi Azikiwe Airport', city: 'Abuja', countryIso2: 'NG', timezone: 'Africa/Lagos', latitude: 9.0068, longitude: 7.2630 },
  { iataCode: 'DKR', name: 'Blaise Diagne Airport', city: 'Dakar', countryIso2: 'SN', timezone: 'Africa/Dakar', latitude: 14.6713, longitude: -17.0724 },
  { iataCode: 'COO', name: 'Cadjehoun Airport', city: 'Cotonou', countryIso2: 'BJ', timezone: 'Africa/Porto-Novo', latitude: 6.3572, longitude: 2.3842 },
  { iataCode: 'OUA', name: 'Ouagadougou Airport', city: 'Ouagadougou', countryIso2: 'BF', timezone: 'Africa/Ouagadougou', latitude: 12.3532, longitude: -1.5124 },
  { iataCode: 'BJM', name: 'Bujumbura Airport', city: 'Bujumbura', countryIso2: 'BI', timezone: 'Africa/Bujumbura', latitude: -3.3240, longitude: 29.3186 },
  { iataCode: 'WDH', name: 'Hosea Kutako Airport', city: 'Windhoek', countryIso2: 'NA', timezone: 'Africa/Windhoek', latitude: -22.4799, longitude: 17.4709 },
  { iataCode: 'GBE', name: 'Sir Seretse Khama Airport', city: 'Gaborone', countryIso2: 'BW', timezone: 'Africa/Gaborone', latitude: -24.5552, longitude: 25.9182 },
  { iataCode: 'VFA', name: 'Victoria Falls Airport', city: 'Victoria Falls', countryIso2: 'ZW', timezone: 'Africa/Harare', latitude: -18.0959, longitude: 25.8390 },
  { iataCode: 'BOG', name: 'El Dorado International Airport', city: 'Bogota', countryIso2: 'CO', timezone: 'America/Bogota', latitude: 4.7016, longitude: -74.1469 },
  { iataCode: 'UIO', name: 'Mariscal Sucre Airport', city: 'Quito', countryIso2: 'EC', timezone: 'America/Guayaquil', latitude: -0.1357, longitude: -78.3611 },
  { iataCode: 'LIM', name: 'Jorge Chavez Airport', city: 'Lima', countryIso2: 'PE', timezone: 'America/Lima', latitude: -12.0219, longitude: -77.1143 },
  { iataCode: 'SCL', name: 'Arturo Merino Benitez Airport', city: 'Santiago', countryIso2: 'CL', timezone: 'America/Santiago', latitude: -33.3930, longitude: -70.7858 },
  { iataCode: 'MVD', name: 'Carrasco International Airport', city: 'Montevideo', countryIso2: 'UY', timezone: 'America/Montevideo', latitude: -34.8384, longitude: -56.0308 },
  { iataCode: 'ASU', name: 'Silvio Pettirossi Airport', city: 'Asuncion', countryIso2: 'PY', timezone: 'America/Asuncion', latitude: -25.2399, longitude: -57.5192 },
  { iataCode: 'VVI', name: 'Viru Viru International Airport', city: 'Santa Cruz', countryIso2: 'BO', timezone: 'America/La_Paz', latitude: -17.6448, longitude: -63.1354 },
  { iataCode: 'PTY', name: 'Tocumen International Airport', city: 'Panama City', countryIso2: 'PA', timezone: 'America/Panama', latitude: 9.0714, longitude: -79.3835 },
  { iataCode: 'SJO', name: 'Juan Santamaria Airport', city: 'San Jose', countryIso2: 'CR', timezone: 'America/Costa_Rica', latitude: 9.9939, longitude: -84.2088 },
  { iataCode: 'SAL', name: 'El Salvador Airport', city: 'San Salvador', countryIso2: 'SV', timezone: 'America/El_Salvador', latitude: 13.4409, longitude: -89.0557 },
  { iataCode: 'GUA', name: 'La Aurora Airport', city: 'Guatemala City', countryIso2: 'GT', timezone: 'America/Guatemala', latitude: 14.5833, longitude: -90.5275 },
  { iataCode: 'BZE', name: 'Philip Goldson Airport', city: 'Belize City', countryIso2: 'BZ', timezone: 'America/Belize', latitude: 17.5391, longitude: -88.3082 },
  { iataCode: 'SDQ', name: 'Las Americas Airport', city: 'Santo Domingo', countryIso2: 'DO', timezone: 'America/Santo_Domingo', latitude: 18.4297, longitude: -69.6689 },
  { iataCode: 'PUJ', name: 'Punta Cana International Airport', city: 'Punta Cana', countryIso2: 'DO', timezone: 'America/Santo_Domingo', latitude: 18.5674, longitude: -68.3634 },
  { iataCode: 'KIN', name: 'Norman Manley Airport', city: 'Kingston', countryIso2: 'JM', timezone: 'America/Jamaica', latitude: 17.9357, longitude: -76.7875 },
  { iataCode: 'MBJ', name: 'Sangster International Airport', city: 'Montego Bay', countryIso2: 'JM', timezone: 'America/Jamaica', latitude: 18.5037, longitude: -77.9134 },
  { iataCode: 'NAS', name: 'Lynden Pindling Airport', city: 'Nassau', countryIso2: 'BS', timezone: 'America/Nassau', latitude: 25.0390, longitude: -77.4662 },
  { iataCode: 'BGI', name: 'Grantley Adams Airport', city: 'Bridgetown', countryIso2: 'BB', timezone: 'America/Barbados', latitude: 13.0746, longitude: -59.4925 },
  { iataCode: 'ANU', name: 'VC Bird International Airport', city: 'St Johns', countryIso2: 'AG', timezone: 'America/Antigua', latitude: 17.1367, longitude: -61.7927 },
];
