export const REFERENCE_DATA_SEED = {
  countries: [
    { name: 'Afghanistan', iso2: 'AF', iso3: 'AFG', dialCode: '+93', currencyCode: 'AFN', continent: 'Asia' },
    { name: 'Albania', iso2: 'AL', iso3: 'ALB', dialCode: '+355', currencyCode: 'ALL', continent: 'Europe' },
    { name: 'Algeria', iso2: 'DZ', iso3: 'DZA', dialCode: '+213', currencyCode: 'DZD', continent: 'Africa' },
    { name: 'Argentina', iso2: 'AR', iso3: 'ARG', dialCode: '+54', currencyCode: 'ARS', continent: 'South America' },
    { name: 'Australia', iso2: 'AU', iso3: 'AUS', dialCode: '+61', currencyCode: 'AUD', continent: 'Oceania' },
    { name: 'Austria', iso2: 'AT', iso3: 'AUT', dialCode: '+43', currencyCode: 'EUR', continent: 'Europe' },
    { name: 'Azerbaijan', iso2: 'AZ', iso3: 'AZE', dialCode: '+994', currencyCode: 'AZN', continent: 'Asia' },
    { name: 'Bahrain', iso2: 'BH', iso3: 'BHR', dialCode: '+973', currencyCode: 'BHD', continent: 'Asia' },
    { name: 'Bangladesh', iso2: 'BD', iso3: 'BGD', dialCode: '+880', currencyCode: 'BDT', continent: 'Asia' },
    { name: 'Belgium', iso2: 'BE', iso3: 'BEL', dialCode: '+32', currencyCode: 'EUR', continent: 'Europe' },
    { name: 'Bhutan', iso2: 'BT', iso3: 'BTN', dialCode: '+975', currencyCode: 'BTN', continent: 'Asia' },
    { name: 'Brazil', iso2: 'BR', iso3: 'BRA', dialCode: '+55', currencyCode: 'BRL', continent: 'South America' },
    { name: 'Brunei', iso2: 'BN', iso3: 'BRN', dialCode: '+673', currencyCode: 'BND', continent: 'Asia' },
    { name: 'Cambodia', iso2: 'KH', iso3: 'KHM', dialCode: '+855', currencyCode: 'KHR', continent: 'Asia' },
    { name: 'Canada', iso2: 'CA', iso3: 'CAN', dialCode: '+1', currencyCode: 'CAD', continent: 'North America' },
    { name: 'China', iso2: 'CN', iso3: 'CHN', dialCode: '+86', currencyCode: 'CNY', continent: 'Asia' },
    { name: 'Denmark', iso2: 'DK', iso3: 'DNK', dialCode: '+45', currencyCode: 'DKK', continent: 'Europe' },
    { name: 'Egypt', iso2: 'EG', iso3: 'EGY', dialCode: '+20', currencyCode: 'EGP', continent: 'Africa' },
    { name: 'Ethiopia', iso2: 'ET', iso3: 'ETH', dialCode: '+251', currencyCode: 'ETB', continent: 'Africa' },
    { name: 'France', iso2: 'FR', iso3: 'FRA', dialCode: '+33', currencyCode: 'EUR', continent: 'Europe' },
    { name: 'Germany', iso2: 'DE', iso3: 'DEU', dialCode: '+49', currencyCode: 'EUR', continent: 'Europe' },
    { name: 'Ghana', iso2: 'GH', iso3: 'GHA', dialCode: '+233', currencyCode: 'GHS', continent: 'Africa' },
    { name: 'Greece', iso2: 'GR', iso3: 'GRC', dialCode: '+30', currencyCode: 'EUR', continent: 'Europe' },
    { name: 'Hong Kong', iso2: 'HK', iso3: 'HKG', dialCode: '+852', currencyCode: 'HKD', continent: 'Asia' },
    { name: 'India', iso2: 'IN', iso3: 'IND', dialCode: '+91', currencyCode: 'INR', continent: 'Asia' },
    { name: 'Indonesia', iso2: 'ID', iso3: 'IDN', dialCode: '+62', currencyCode: 'IDR', continent: 'Asia' },
    { name: 'Iran', iso2: 'IR', iso3: 'IRN', dialCode: '+98', currencyCode: 'IRR', continent: 'Asia' },
    { name: 'Iraq', iso2: 'IQ', iso3: 'IRQ', dialCode: '+964', currencyCode: 'IQD', continent: 'Asia' },
    { name: 'Ireland', iso2: 'IE', iso3: 'IRL', dialCode: '+353', currencyCode: 'EUR', continent: 'Europe' },
    { name: 'Italy', iso2: 'IT', iso3: 'ITA', dialCode: '+39', currencyCode: 'EUR', continent: 'Europe' },
    { name: 'Japan', iso2: 'JP', iso3: 'JPN', dialCode: '+81', currencyCode: 'JPY', continent: 'Asia' },
    { name: 'Jordan', iso2: 'JO', iso3: 'JOR', dialCode: '+962', currencyCode: 'JOD', continent: 'Asia' },
    { name: 'Kenya', iso2: 'KE', iso3: 'KEN', dialCode: '+254', currencyCode: 'KES', continent: 'Africa' },
    { name: 'Kuwait', iso2: 'KW', iso3: 'KWT', dialCode: '+965', currencyCode: 'KWD', continent: 'Asia' },
    { name: 'Lebanon', iso2: 'LB', iso3: 'LBN', dialCode: '+961', currencyCode: 'LBP', continent: 'Asia' },
    { name: 'Malaysia', iso2: 'MY', iso3: 'MYS', dialCode: '+60', currencyCode: 'MYR', continent: 'Asia' },
    { name: 'Maldives', iso2: 'MV', iso3: 'MDV', dialCode: '+960', currencyCode: 'MVR', continent: 'Asia' },
    { name: 'Mauritius', iso2: 'MU', iso3: 'MUS', dialCode: '+230', currencyCode: 'MUR', continent: 'Africa' },
    { name: 'Mexico', iso2: 'MX', iso3: 'MEX', dialCode: '+52', currencyCode: 'MXN', continent: 'North America' },
    { name: 'Morocco', iso2: 'MA', iso3: 'MAR', dialCode: '+212', currencyCode: 'MAD', continent: 'Africa' },
    { name: 'Myanmar', iso2: 'MM', iso3: 'MMR', dialCode: '+95', currencyCode: 'MMK', continent: 'Asia' },
    { name: 'Nepal', iso2: 'NP', iso3: 'NPL', dialCode: '+977', currencyCode: 'NPR', continent: 'Asia' },
    { name: 'Netherlands', iso2: 'NL', iso3: 'NLD', dialCode: '+31', currencyCode: 'EUR', continent: 'Europe' },
    { name: 'New Zealand', iso2: 'NZ', iso3: 'NZL', dialCode: '+64', currencyCode: 'NZD', continent: 'Oceania' },
    { name: 'Nigeria', iso2: 'NG', iso3: 'NGA', dialCode: '+234', currencyCode: 'NGN', continent: 'Africa' },
    { name: 'Norway', iso2: 'NO', iso3: 'NOR', dialCode: '+47', currencyCode: 'NOK', continent: 'Europe' },
    { name: 'Oman', iso2: 'OM', iso3: 'OMN', dialCode: '+968', currencyCode: 'OMR', continent: 'Asia' },
    { name: 'Pakistan', iso2: 'PK', iso3: 'PAK', dialCode: '+92', currencyCode: 'PKR', continent: 'Asia' },
    { name: 'Philippines', iso2: 'PH', iso3: 'PHL', dialCode: '+63', currencyCode: 'PHP', continent: 'Asia' },
    { name: 'Poland', iso2: 'PL', iso3: 'POL', dialCode: '+48', currencyCode: 'PLN', continent: 'Europe' },
    { name: 'Portugal', iso2: 'PT', iso3: 'PRT', dialCode: '+351', currencyCode: 'EUR', continent: 'Europe' },
    { name: 'Qatar', iso2: 'QA', iso3: 'QAT', dialCode: '+974', currencyCode: 'QAR', continent: 'Asia' },
    { name: 'Romania', iso2: 'RO', iso3: 'ROU', dialCode: '+40', currencyCode: 'RON', continent: 'Europe' },
    { name: 'Russia', iso2: 'RU', iso3: 'RUS', dialCode: '+7', currencyCode: 'RUB', continent: 'Europe' },
    { name: 'Saudi Arabia', iso2: 'SA', iso3: 'SAU', dialCode: '+966', currencyCode: 'SAR', continent: 'Asia' },
    { name: 'Singapore', iso2: 'SG', iso3: 'SGP', dialCode: '+65', currencyCode: 'SGD', continent: 'Asia' },
    { name: 'South Africa', iso2: 'ZA', iso3: 'ZAF', dialCode: '+27', currencyCode: 'ZAR', continent: 'Africa' },
    { name: 'South Korea', iso2: 'KR', iso3: 'KOR', dialCode: '+82', currencyCode: 'KRW', continent: 'Asia' },
    { name: 'Spain', iso2: 'ES', iso3: 'ESP', dialCode: '+34', currencyCode: 'EUR', continent: 'Europe' },
    { name: 'Sri Lanka', iso2: 'LK', iso3: 'LKA', dialCode: '+94', currencyCode: 'LKR', continent: 'Asia' },
    { name: 'Sweden', iso2: 'SE', iso3: 'SWE', dialCode: '+46', currencyCode: 'SEK', continent: 'Europe' },
    { name: 'Switzerland', iso2: 'CH', iso3: 'CHE', dialCode: '+41', currencyCode: 'CHF', continent: 'Europe' },
    { name: 'Thailand', iso2: 'TH', iso3: 'THA', dialCode: '+66', currencyCode: 'THB', continent: 'Asia' },
    { name: 'Turkey', iso2: 'TR', iso3: 'TUR', dialCode: '+90', currencyCode: 'TRY', continent: 'Europe' },
    { name: 'UAE', iso2: 'AE', iso3: 'ARE', dialCode: '+971', currencyCode: 'AED', continent: 'Asia' },
    { name: 'United Kingdom', iso2: 'GB', iso3: 'GBR', dialCode: '+44', currencyCode: 'GBP', continent: 'Europe' },
    { name: 'USA', iso2: 'US', iso3: 'USA', dialCode: '+1', currencyCode: 'USD', continent: 'North America' },
    { name: 'Uzbekistan', iso2: 'UZ', iso3: 'UZB', dialCode: '+998', currencyCode: 'UZS', continent: 'Asia' },
    { name: 'Vietnam', iso2: 'VN', iso3: 'VNM', dialCode: '+84', currencyCode: 'VND', continent: 'Asia' },
    { name: 'Yemen', iso2: 'YE', iso3: 'YEM', dialCode: '+967', currencyCode: 'YER', continent: 'Asia' },
  ],

  currencies: [
    { code: 'USD', name: 'US Dollar', symbol: '$', decimalPlaces: 2 },
    { code: 'EUR', name: 'Euro', symbol: '€', decimalPlaces: 2 },
    { code: 'GBP', name: 'British Pound', symbol: '£', decimalPlaces: 2 },
    { code: 'JPY', name: 'Japanese Yen', symbol: '¥', decimalPlaces: 0 },
    { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', decimalPlaces: 2 },
    { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', decimalPlaces: 2 },
    { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', decimalPlaces: 2 },
    { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', decimalPlaces: 2 },
    { code: 'INR', name: 'Indian Rupee', symbol: '₹', decimalPlaces: 2 },
    { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', decimalPlaces: 2 },
    { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', decimalPlaces: 2 },
    { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', decimalPlaces: 2 },
    { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', decimalPlaces: 2 },
    { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', decimalPlaces: 3 },
    { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', decimalPlaces: 3 },
    { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', decimalPlaces: 3 },
    { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', decimalPlaces: 2 },
    { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', decimalPlaces: 2 },
    { code: 'THB', name: 'Thai Baht', symbol: '฿', decimalPlaces: 2 },
    { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', decimalPlaces: 0 },
    { code: 'KRW', name: 'South Korean Won', symbol: '₩', decimalPlaces: 0 },
    { code: 'TRY', name: 'Turkish Lira', symbol: '₺', decimalPlaces: 2 },
    { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', decimalPlaces: 2 },
    { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', decimalPlaces: 2 },
    { code: 'ZAR', name: 'South African Rand', symbol: 'R', decimalPlaces: 2 },
    { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', decimalPlaces: 2 },
    { code: 'MXN', name: 'Mexican Peso', symbol: '$', decimalPlaces: 2 },
    { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', decimalPlaces: 2 },
    { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'රු', decimalPlaces: 2 },
    { code: 'NPR', name: 'Nepalese Rupee', symbol: 'रू', decimalPlaces: 2 },
  ],

  airlines: [
    { iataCode: 'QR', icaoCode: 'QTR', name: 'Qatar Airways', countryIso2: 'QA' },
    { iataCode: 'EK', icaoCode: 'UAE', name: 'Emirates', countryIso2: 'AE' },
    { iataCode: 'EY', icaoCode: 'ETD', name: 'Etihad Airways', countryIso2: 'AE' },
    { iataCode: 'SV', icaoCode: 'SVA', name: 'Saudia', countryIso2: 'SA' },
    { iataCode: 'WY', icaoCode: 'OMA', name: 'Oman Air', countryIso2: 'OM' },
    { iataCode: 'GF', icaoCode: 'GFA', name: 'Gulf Air', countryIso2: 'BH' },
    { iataCode: 'KU', icaoCode: 'KAC', name: 'Kuwait Airways', countryIso2: 'KW' },
    { iataCode: 'TK', icaoCode: 'THY', name: 'Turkish Airlines', countryIso2: 'TR' },
    { iataCode: 'BG', icaoCode: 'BBC', name: 'Biman Bangladesh Airlines', countryIso2: 'BD' },
    { iataCode: 'SG', icaoCode: 'SEJ', name: 'SpiceJet', countryIso2: 'IN' },
    { iataCode: '6E', icaoCode: 'IGO', name: 'IndiGo', countryIso2: 'IN' },
    { iataCode: 'AI', icaoCode: 'AIC', name: 'Air India', countryIso2: 'IN' },
    { iataCode: 'UK', icaoCode: 'VTI', name: 'Vistara', countryIso2: 'IN' },
    { iataCode: 'MH', icaoCode: 'MAS', name: 'Malaysia Airlines', countryIso2: 'MY' },
    { iataCode: 'AK', icaoCode: 'AXM', name: 'AirAsia', countryIso2: 'MY' },
    { iataCode: 'SQ', icaoCode: 'SIA', name: 'Singapore Airlines', countryIso2: 'SG' },
    { iataCode: 'TG', icaoCode: 'THA', name: 'Thai Airways', countryIso2: 'TH' },
    { iataCode: 'CX', icaoCode: 'CPA', name: 'Cathay Pacific', countryIso2: 'HK' },
    { iataCode: 'BA', icaoCode: 'BAW', name: 'British Airways', countryIso2: 'GB' },
    { iataCode: 'LH', icaoCode: 'DLH', name: 'Lufthansa', countryIso2: 'DE' },
    { iataCode: 'AF', icaoCode: 'AFR', name: 'Air France', countryIso2: 'FR' },
    { iataCode: 'KL', icaoCode: 'KLM', name: 'KLM Royal Dutch Airlines', countryIso2: 'NL' },
    { iataCode: 'DL', icaoCode: 'DAL', name: 'Delta Air Lines', countryIso2: 'US' },
    { iataCode: 'UA', icaoCode: 'UAL', name: 'United Airlines', countryIso2: 'US' },
    { iataCode: 'AA', icaoCode: 'AAL', name: 'American Airlines', countryIso2: 'US' },
    { iataCode: 'QF', icaoCode: 'QFA', name: 'Qantas', countryIso2: 'AU' },
    { iataCode: 'ET', icaoCode: 'ETH', name: 'Ethiopian Airlines', countryIso2: 'ET' },
    { iataCode: 'MS', icaoCode: 'MSR', name: 'EgyptAir', countryIso2: 'EG' },
    { iataCode: 'FZ', icaoCode: 'FDB', name: 'flydubai', countryIso2: 'AE' },
    { iataCode: 'G9', icaoCode: 'ABY', name: 'Air Arabia', countryIso2: 'AE' },
    { iataCode: 'J9', icaoCode: 'JZR', name: 'Jazeera Airways', countryIso2: 'KW' },
    { iataCode: 'OV', icaoCode: 'OMS', name: 'SalamAir', countryIso2: 'OM' },
    { iataCode: 'BS', icaoCode: 'UBG', name: 'US-Bangla Airlines', countryIso2: 'BD' },
    { iataCode: 'PR', icaoCode: 'PAL', name: 'Philippine Airlines', countryIso2: 'PH' },
    { iataCode: 'GA', icaoCode: 'GIA', name: 'Garuda Indonesia', countryIso2: 'ID' },
    { iataCode: 'UL', icaoCode: 'ALK', name: 'SriLankan Airlines', countryIso2: 'LK' },
    { iataCode: 'RA', icaoCode: 'RNA', name: 'Nepal Airlines', countryIso2: 'NP' },
    { iataCode: 'KE', icaoCode: 'KAL', name: 'Korean Air', countryIso2: 'KR' },
    { iataCode: 'OZ', icaoCode: 'AAR', name: 'Asiana Airlines', countryIso2: 'KR' },
    { iataCode: 'CZ', icaoCode: 'CSN', name: 'China Southern', countryIso2: 'CN' },
    { iataCode: 'MU', icaoCode: 'CES', name: 'China Eastern', countryIso2: 'CN' },
    { iataCode: 'CA', icaoCode: 'CCA', name: 'Air China', countryIso2: 'CN' },
    { iataCode: 'VN', icaoCode: 'HVN', name: 'Vietnam Airlines', countryIso2: 'VN' },
    { iataCode: 'BR', icaoCode: 'EVA', name: 'EVA Air', countryIso2: 'TW' },
    { iataCode: 'SU', icaoCode: 'AFL', name: 'Aeroflot', countryIso2: 'RU' },
    { iataCode: 'PC', icaoCode: 'PGT', name: 'Pegasus Airlines', countryIso2: 'TR' },
    { iataCode: 'W6', icaoCode: 'WZZ', name: 'Wizz Air', countryIso2: 'HU' },
    { iataCode: 'FR', icaoCode: 'RYR', name: 'Ryanair', countryIso2: 'IE' },
    { iataCode: 'U2', icaoCode: 'EZY', name: 'easyJet', countryIso2: 'GB' },
    { iataCode: 'ME', icaoCode: 'MEA', name: 'Middle East Airlines', countryIso2: 'LB' },
    { iataCode: 'RJ', icaoCode: 'RJA', name: 'Royal Jordanian', countryIso2: 'JO' },
    { iataCode: 'IR', icaoCode: 'IRA', name: 'Iran Air', countryIso2: 'IR' },
    { iataCode: 'PK', icaoCode: 'PIA', name: 'Pakistan International', countryIso2: 'PK' },
    { iataCode: 'WB', icaoCode: 'RWD', name: 'RwandAir', countryIso2: 'RW' },
    { iataCode: 'KQ', icaoCode: 'KQA', name: 'Kenya Airways', countryIso2: 'KE' },
    { iataCode: 'AT', icaoCode: 'RAM', name: 'Royal Air Maroc', countryIso2: 'MA' },
  ],

  airports: [
    { iataCode: 'DXB', name: 'Dubai International Airport', city: 'Dubai', countryIso2: 'AE', timezone: 'Asia/Dubai', latitude: 25.2532, longitude: 55.3657 },
    { iataCode: 'AUH', name: 'Abu Dhabi International Airport', city: 'Abu Dhabi', countryIso2: 'AE', timezone: 'Asia/Dubai', latitude: 24.4331, longitude: 54.6511 },
    { iataCode: 'SHJ', name: 'Sharjah International Airport', city: 'Sharjah', countryIso2: 'AE', timezone: 'Asia/Dubai', latitude: 25.3286, longitude: 55.5172 },
    { iataCode: 'DOH', name: 'Hamad International Airport', city: 'Doha', countryIso2: 'QA', timezone: 'Asia/Qatar', latitude: 25.2731, longitude: 51.6081 },
    { iataCode: 'JED', name: 'King Abdulaziz International Airport', city: 'Jeddah', countryIso2: 'SA', timezone: 'Asia/Riyadh', latitude: 21.6796, longitude: 39.1565 },
    { iataCode: 'RUH', name: 'King Khalid International Airport', city: 'Riyadh', countryIso2: 'SA', timezone: 'Asia/Riyadh', latitude: 24.9576, longitude: 46.6988 },
    { iataCode: 'MED', name: 'Prince Mohammad Bin Abdulaziz Airport', city: 'Medina', countryIso2: 'SA', timezone: 'Asia/Riyadh', latitude: 24.5534, longitude: 39.7051 },
    { iataCode: 'MCT', name: 'Muscat International Airport', city: 'Muscat', countryIso2: 'OM', timezone: 'Asia/Muscat', latitude: 23.5933, longitude: 58.2843 },
    { iataCode: 'KWI', name: 'Kuwait International Airport', city: 'Kuwait City', countryIso2: 'KW', timezone: 'Asia/Kuwait', latitude: 29.2266, longitude: 47.9689 },
    { iataCode: 'BAH', name: 'Bahrain International Airport', city: 'Manama', countryIso2: 'BH', timezone: 'Asia/Bahrain', latitude: 26.2708, longitude: 50.6336 },
    { iataCode: 'IST', name: 'Istanbul Airport', city: 'Istanbul', countryIso2: 'TR', timezone: 'Europe/Istanbul', latitude: 41.2608, longitude: 28.7418 },
    { iataCode: 'SAW', name: 'Sabiha Gokcen International Airport', city: 'Istanbul', countryIso2: 'TR', timezone: 'Europe/Istanbul', latitude: 40.8986, longitude: 29.3092 },
    { iataCode: 'DAC', name: 'Hazrat Shahjalal International Airport', city: 'Dhaka', countryIso2: 'BD', timezone: 'Asia/Dhaka', latitude: 23.8433, longitude: 90.3978 },
    { iataCode: 'CGP', name: 'Shah Amanat International Airport', city: 'Chittagong', countryIso2: 'BD', timezone: 'Asia/Dhaka', latitude: 22.2496, longitude: 91.8133 },
    { iataCode: 'ZYL', name: 'Osmani International Airport', city: 'Sylhet', countryIso2: 'BD', timezone: 'Asia/Dhaka', latitude: 24.9633, longitude: 91.8690 },
    { iataCode: 'CCU', name: 'Netaji Subhas Chandra Bose Airport', city: 'Kolkata', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 22.6547, longitude: 88.4467 },
    { iataCode: 'DEL', name: 'Indira Gandhi International Airport', city: 'Delhi', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 28.5562, longitude: 77.1000 },
    { iataCode: 'BOM', name: 'Chhatrapati Shivaji Maharaj Airport', city: 'Mumbai', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 19.0896, longitude: 72.8656 },
    { iataCode: 'MAA', name: 'Chennai International Airport', city: 'Chennai', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 12.9941, longitude: 80.1709 },
    { iataCode: 'BLR', name: 'Kempegowda International Airport', city: 'Bangalore', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 13.1986, longitude: 77.7066 },
    { iataCode: 'HYD', name: 'Rajiv Gandhi International Airport', city: 'Hyderabad', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 17.2313, longitude: 78.4299 },
    { iataCode: 'COK', name: 'Cochin International Airport', city: 'Kochi', countryIso2: 'IN', timezone: 'Asia/Kolkata', latitude: 10.1520, longitude: 76.4019 },
    { iataCode: 'KUL', name: 'Kuala Lumpur International Airport', city: 'Kuala Lumpur', countryIso2: 'MY', timezone: 'Asia/Kuala_Lumpur', latitude: 2.7456, longitude: 101.7099 },
    { iataCode: 'SIN', name: 'Singapore Changi Airport', city: 'Singapore', countryIso2: 'SG', timezone: 'Asia/Singapore', latitude: 1.3644, longitude: 103.9915 },
    { iataCode: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok', countryIso2: 'TH', timezone: 'Asia/Bangkok', latitude: 13.6900, longitude: 100.7501 },
    { iataCode: 'DMK', name: 'Don Mueang International Airport', city: 'Bangkok', countryIso2: 'TH', timezone: 'Asia/Bangkok', latitude: 13.9125, longitude: 100.6067 },
    { iataCode: 'HKT', name: 'Phuket International Airport', city: 'Phuket', countryIso2: 'TH', timezone: 'Asia/Bangkok', latitude: 8.1132, longitude: 98.3169 },
    { iataCode: 'HKG', name: 'Hong Kong International Airport', city: 'Hong Kong', countryIso2: 'HK', timezone: 'Asia/Hong_Kong', latitude: 22.3080, longitude: 113.9185 },
    { iataCode: 'LHR', name: 'London Heathrow Airport', city: 'London', countryIso2: 'GB', timezone: 'Europe/London', latitude: 51.4700, longitude: -0.4543 },
    { iataCode: 'LGW', name: 'London Gatwick Airport', city: 'London', countryIso2: 'GB', timezone: 'Europe/London', latitude: 51.1481, longitude: -0.1903 },
    { iataCode: 'MAN', name: 'Manchester Airport', city: 'Manchester', countryIso2: 'GB', timezone: 'Europe/London', latitude: 53.3537, longitude: -2.2750 },
    { iataCode: 'CDG', name: 'Charles de Gaulle Airport', city: 'Paris', countryIso2: 'FR', timezone: 'Europe/Paris', latitude: 49.0097, longitude: 2.5479 },
    { iataCode: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt', countryIso2: 'DE', timezone: 'Europe/Berlin', latitude: 50.0379, longitude: 8.5622 },
    { iataCode: 'AMS', name: 'Amsterdam Airport Schiphol', city: 'Amsterdam', countryIso2: 'NL', timezone: 'Europe/Amsterdam', latitude: 52.3105, longitude: 4.7683 },
    { iataCode: 'FCO', name: 'Leonardo da Vinci International Airport', city: 'Rome', countryIso2: 'IT', timezone: 'Europe/Rome', latitude: 41.8003, longitude: 12.2389 },
    { iataCode: 'MAD', name: 'Adolfo Suarez Madrid-Barajas Airport', city: 'Madrid', countryIso2: 'ES', timezone: 'Europe/Madrid', latitude: 40.4936, longitude: -3.5668 },
    { iataCode: 'BCN', name: 'Barcelona-El Prat Airport', city: 'Barcelona', countryIso2: 'ES', timezone: 'Europe/Madrid', latitude: 41.2969, longitude: 2.0783 },
    { iataCode: 'ZRH', name: 'Zurich Airport', city: 'Zurich', countryIso2: 'CH', timezone: 'Europe/Zurich', latitude: 47.4582, longitude: 8.5555 },
    { iataCode: 'JFK', name: 'John F Kennedy International Airport', city: 'New York', countryIso2: 'US', timezone: 'America/New_York', latitude: 40.6413, longitude: -73.7781 },
    { iataCode: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', countryIso2: 'US', timezone: 'America/Los_Angeles', latitude: 33.9416, longitude: -118.4085 },
    { iataCode: 'ORD', name: "O'Hare International Airport", city: 'Chicago', countryIso2: 'US', timezone: 'America/Chicago', latitude: 41.9742, longitude: -87.9073 },
    { iataCode: 'IAH', name: 'George Bush Intercontinental Airport', city: 'Houston', countryIso2: 'US', timezone: 'America/Chicago', latitude: 29.9902, longitude: -95.3368 },
    { iataCode: 'YYZ', name: 'Toronto Pearson International Airport', city: 'Toronto', countryIso2: 'CA', timezone: 'America/Toronto', latitude: 43.6777, longitude: -79.6248 },
    { iataCode: 'SYD', name: 'Sydney Kingsford Smith Airport', city: 'Sydney', countryIso2: 'AU', timezone: 'Australia/Sydney', latitude: -33.9399, longitude: 151.1753 },
    { iataCode: 'MEL', name: 'Melbourne Airport', city: 'Melbourne', countryIso2: 'AU', timezone: 'Australia/Melbourne', latitude: -37.6690, longitude: 144.8410 },
    { iataCode: 'CAI', name: 'Cairo International Airport', city: 'Cairo', countryIso2: 'EG', timezone: 'Africa/Cairo', latitude: 30.1114, longitude: 31.4003 },
    { iataCode: 'NBO', name: 'Jomo Kenyatta International Airport', city: 'Nairobi', countryIso2: 'KE', timezone: 'Africa/Nairobi', latitude: -1.3192, longitude: 36.9273 },
    { iataCode: 'ADD', name: 'Bole International Airport', city: 'Addis Ababa', countryIso2: 'ET', timezone: 'Africa/Addis_Ababa', latitude: 8.9779, longitude: 38.7993 },
    { iataCode: 'CMN', name: 'Mohammed V International Airport', city: 'Casablanca', countryIso2: 'MA', timezone: 'Africa/Casablanca', latitude: 33.3675, longitude: -7.5892 },
    { iataCode: 'LOS', name: 'Murtala Muhammed International Airport', city: 'Lagos', countryIso2: 'NG', timezone: 'Africa/Lagos', latitude: 6.5774, longitude: 3.3210 },
    { iataCode: 'NRT', name: 'Narita International Airport', city: 'Tokyo', countryIso2: 'JP', timezone: 'Asia/Tokyo', latitude: 35.7719, longitude: 140.3925 },
    { iataCode: 'HND', name: 'Haneda Airport', city: 'Tokyo', countryIso2: 'JP', timezone: 'Asia/Tokyo', latitude: 35.5533, longitude: 139.7811 },
    { iataCode: 'ICN', name: 'Incheon International Airport', city: 'Seoul', countryIso2: 'KR', timezone: 'Asia/Seoul', latitude: 37.4602, longitude: 126.4407 },
    { iataCode: 'PEK', name: 'Beijing Capital International Airport', city: 'Beijing', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 40.0799, longitude: 116.6031 },
    { iataCode: 'PVG', name: 'Shanghai Pudong International Airport', city: 'Shanghai', countryIso2: 'CN', timezone: 'Asia/Shanghai', latitude: 31.1443, longitude: 121.8083 },
    { iataCode: 'CGK', name: 'Soekarno-Hatta International Airport', city: 'Jakarta', countryIso2: 'ID', timezone: 'Asia/Jakarta', latitude: -6.1256, longitude: 106.6558 },
    { iataCode: 'MNL', name: 'Ninoy Aquino International Airport', city: 'Manila', countryIso2: 'PH', timezone: 'Asia/Manila', latitude: 14.5086, longitude: 121.0198 },
    { iataCode: 'KTM', name: 'Tribhuvan International Airport', city: 'Kathmandu', countryIso2: 'NP', timezone: 'Asia/Kathmandu', latitude: 27.6966, longitude: 85.3591 },
    { iataCode: 'CMB', name: 'Bandaranaike International Airport', city: 'Colombo', countryIso2: 'LK', timezone: 'Asia/Colombo', latitude: 7.1808, longitude: 79.8841 },
    { iataCode: 'MLE', name: 'Velana International Airport', city: 'Male', countryIso2: 'MV', timezone: 'Indian/Maldives', latitude: 4.1918, longitude: 73.5291 },
    { iataCode: 'KBL', name: 'Kabul International Airport', city: 'Kabul', countryIso2: 'AF', timezone: 'Asia/Kabul', latitude: 34.5659, longitude: 69.2123 },
    { iataCode: 'AMM', name: 'Queen Alia International Airport', city: 'Amman', countryIso2: 'JO', timezone: 'Asia/Amman', latitude: 31.7226, longitude: 35.9932 },
    { iataCode: 'BEY', name: 'Beirut-Rafic Hariri International Airport', city: 'Beirut', countryIso2: 'LB', timezone: 'Asia/Beirut', latitude: 33.8209, longitude: 35.4884 },
    { iataCode: 'IKA', name: 'Imam Khomeini International Airport', city: 'Tehran', countryIso2: 'IR', timezone: 'Asia/Tehran', latitude: 35.4161, longitude: 51.1522 },
    { iataCode: 'ISB', name: 'Islamabad International Airport', city: 'Islamabad', countryIso2: 'PK', timezone: 'Asia/Karachi', latitude: 33.5607, longitude: 72.8517 },
    { iataCode: 'LHE', name: 'Allama Iqbal International Airport', city: 'Lahore', countryIso2: 'PK', timezone: 'Asia/Karachi', latitude: 31.5216, longitude: 74.4036 },
    { iataCode: 'KHI', name: 'Jinnah International Airport', city: 'Karachi', countryIso2: 'PK', timezone: 'Asia/Karachi', latitude: 24.9065, longitude: 67.1608 },
    { iataCode: 'GRU', name: 'Sao Paulo-Guarulhos International Airport', city: 'Sao Paulo', countryIso2: 'BR', timezone: 'America/Sao_Paulo', latitude: -23.4356, longitude: -46.4731 },
    { iataCode: 'CPT', name: 'Cape Town International Airport', city: 'Cape Town', countryIso2: 'ZA', timezone: 'Africa/Johannesburg', latitude: -33.9648, longitude: 18.6017 },
    { iataCode: 'MRU', name: 'Sir Seewoosagur Ramgoolam Airport', city: 'Port Louis', countryIso2: 'MU', timezone: 'Indian/Mauritius', latitude: -20.4302, longitude: 57.6836 },
  ],
};

export const CABIN_CLASS_SEED = [
  { code: 'F', name: 'First Class', sortOrder: 1 },
  { code: 'J', name: 'Business Class', sortOrder: 2 },
  { code: 'W', name: 'Premium Economy', sortOrder: 3 },
  { code: 'Y', name: 'Economy Class', sortOrder: 4 },
];
