import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { api } from '@/lib/api';
import { useAuthStore } from '@/stores/auth-store';
import { Employee, EMPLOYEE_STATUSES } from '@/lib/crm';

interface Props { open: boolean; onOpenChange: (o: boolean) => void; employee?: Employee | null; onSaved: () => void; }
interface FormState { employeeCode: string; firstName: string; lastName: string; email: string; phone: string; position: string; status: string; joinedAt: string; }
const empty: FormState = { employeeCode: '', firstName: '', lastName: '', email: '', phone: '', position: '', status: 'ACTIVE', joinedAt: '' };
export function EmployeeFormDialog({ open, onOpenChange, employee, onSaved }: Props) {
  const { activeTenant } = useAuthStore();
  const [form, setForm] = useState<FormState>(empty); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const isEdit = !!employee;
  useEffect(() => { if (open) { setError(''); setForm(employee ? { employeeCode: employee.employeeCode, firstName: employee.firstName, lastName: employee.lastName, email: employee.email ?? '', phone: employee.phone ?? '', position: employee.position ?? '', status: employee.status, joinedAt: employee.joinedAt?.split('T')[0] ?? '' } : empty); } }, [open, employee]);
  const set = (k: keyof FormState, v: string) => setForm((f) => ({ ...f, [k]: v }));
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); if (!activeTenant || !form.employeeCode.trim() || !form.firstName.trim() || !form.lastName.trim()) { setError('Code, first name, and last name are required'); return; }; setSaving(true); setError(''); const payload = { employeeCode: form.employeeCode.trim(), firstName: form.firstName.trim(), lastName: form.lastName.trim(), email: form.email.trim() || undefined, phone: form.phone.trim() || undefined, position: form.position.trim() || undefined, status: form.status, joinedAt: form.joinedAt || undefined }; try { if (isEdit && employee) { await api.put(`/api/v1/tenant/employees/${employee.id}`, payload, { tenantId: activeTenant.id }); toast.success('Employee updated'); } else { await api.post('/api/v1/tenant/employees', payload, { tenantId: activeTenant.id }); toast.success('Employee created'); } onOpenChange(false); onSaved(); } catch (err: any) { setError(err.message); toast.error(err.message); } finally { setSaving(false); } };
  return (<Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>{isEdit ? 'Edit Employee' : 'New Employee'}</DialogTitle><DialogDescription>{isEdit ? 'Update employee details.' : 'Register a new employee.'}</DialogDescription></DialogHeader><form onSubmit={handleSubmit} className="space-y-4">{error && <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}<div className="space-y-2"><Label>Employee Code <span className="text-destructive">*</span></Label><Input value={form.employeeCode} onChange={(e) => set('employeeCode', e.target.value)} placeholder="EMP-001" /></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>First Name <span className="text-destructive">*</span></Label><Input value={form.firstName} onChange={(e) => set('firstName', e.target.value)} /></div><div className="space-y-2"><Label>Last Name <span className="text-destructive">*</span></Label><Input value={form.lastName} onChange={(e) => set('lastName', e.target.value)} /></div></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Email</Label><Input type="email" value={form.email} onChange={(e) => set('email', e.target.value)} /></div><div className="space-y-2"><Label>Phone</Label><Input value={form.phone} onChange={(e) => set('phone', e.target.value)} /></div></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><div className="space-y-2"><Label>Position</Label><Input value={form.position} onChange={(e) => set('position', e.target.value)} /></div><div className="space-y-2"><Label>Status</Label><Select value={form.status} onValueChange={(v) => set('status', v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{EMPLOYEE_STATUSES.map((s) => (<SelectItem key={s} value={s}>{s}</SelectItem>))}</SelectContent></Select></div><div className="space-y-2"><Label>Joined date</Label><Input type="date" value={form.joinedAt} onChange={(e) => set('joinedAt', e.target.value)} /></div></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? 'Saving...' : isEdit ? 'Save' : 'Create'}</Button></DialogFooter></form></DialogContent></Dialog>);
}
